apps/docs/src/pages/components/menu-lists.mdx, packages/react-compass/src/menu-list/menu-list-dropdown-header.styles.ts, packages/react-compass/src/menu-list/menu-list-dropdown-header.tsx, packages/react-compass/src/menu-list/menu-list-dropdown-item.styles.ts, packages/react-compass/src/menu-list/menu-list-dropdown-item.tsx
=> fix dropdown icon, disabled state, focusable

packages/react-compass/src/accordion/accordion-title.styles.ts, packages/react-compass/src/accordion/accordion.styles.ts, packages/react-compass/src/accordion/accordion.tsx
=> fix accordion height, icon position, straigh line

packages/react-compass/src/dialog/dialog.styles.ts, packages/react-compass/src/modal/modal.styles.ts, packages/react-compass/src/sidebar/sidebar.styles.ts, packages/react-compass/src/toast/toast.styles.ts
Updates are following this rule:
https://www.figma.com/file/MQVnynY3v1pI55Cm6l5qHK/CDGNotes?node-id=8%3A2&t=dxBowPGxuJ6gYoa1-4
Ticket link:
https://github.com/comfortdelgro/compass-design/issues/259
=> Applying new definition of zIndex rule

packages/react-compass/src/multiple-dropdown/options/index.tsx
=> feat(dropdown): remove logs

apps/docs/src/components/Popovers.tsx, apps/docs/src/pages/components/popover.mdx, packages/react-compass/src/index.ts, packages/react-compass/src/multiple-dropdown/options/index.tsx, packages/react-compass/src/popover/index.ts, packages/react-compass/src/popover/popover.stories.tsx, packages/react-compass/src/popover/popover.style.ts, packages/react-compass/src/popover/popover.tsx
* Add new Popover component
* Add document for it
=> feat(popover): add new popover component

packages/react-compass/src/checkbox/checkbox.styles.ts, packages/react-compass/src/checkbox/checkbox.tsx
- fix styles for checkbox component
=> [yagin][fix style for checkbox]

packages/react-compass/src/table-v2/react-table-column-header.tsx, packages/react-compass/src/table-v2/react-table.tsx, packages/react-compass/src/table-v2/table-v2.stories.tsx
- update handle sort icon and fix css
=> [yagin][update handle sort icon and fix css]

packages/react-compass/src/popover/popover.tsx
Update for Popover top position
=> Update for Popover top position

packages/react-compass/src/checkbox/checkbox.styles.ts, packages/react-compass/src/table-v2/react-table.tsx, packages/react-compass/src/table-v2/table-v2.stories.tsx
release onchange for user and fix css
=> [yagin][release onchange for user and fix css]

packages/react-compass/src/checkbox/checkbox.styles.ts, packages/react-compass/src/table/table-checkbox-cell.tsx
Fix bug checkbox on table v1
https://github.com/comfortdelgro/compass-design/assets/128688086/0dc43c16-5d7b-46a9-afb8-06911e6fbf2c
=> [fix] bug checkbox table v1

packages/react-compass/src/checkbox/checkbox.styles.ts, packages/react-compass/src/table/table-checkbox-cell.tsx
This reverts commit 71b19f825ac23033391dd5bf91594666459955f8.
=> Revert "[fix] bug checkbox table v1 (#632)"

packages/react-compass/src/calendar/hooks/useCalendarState.ts, packages/react-compass/src/calendar/hooks/useDateSegment.ts, packages/react-compass/src/calendar/utils/common.ts
isInvalid function in calendar common file missing the date is null case
=> fix: calendar null errors

packages/react-compass/src/calendar/hooks/useDateField.ts, packages/react-compass/src/calendar/hooks/useDateFieldState.ts, packages/react-compass/src/calendar/types/common.types.ts, packages/react-compass/src/date-picker/date-picker.stories.tsx
fix: year delete when month delete
feature: focus next value when finish typing date
=> fix: year delete when month delete, feature: focus next value when finish typing date

packages/react-compass/src/calendar/hooks/useCalendarGrid.ts
Remove hardcoded weekdays, apply localization weekdays
=> fix: calendar weekdays missing localizability

packages/react-compass/src/tag-box-v2/tag-box-v2.styles.ts, packages/react-compass/src/tag-box-v2/tag-box-v2.tsx
- fontSize: '$label1', //14px
- lineHeight: '$normal', //21px
- change div--> label for label tag
- background : gray20
- add props isDisabled for wrapper
=> [yagin][fix some styles of tag box v2]

apps/docs/src/components/DatePickers.tsx
Date range picker logic and types has been changed in the library but the docs is not updated
**2) Changes**
Change type for controlled date range picker in docs
**3) Impact**
No impact
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> fix: docs datepicker lint

apps/docs/src/pages/_document.tsx, apps/docs/src/pages/components/accordions.mdx
- [Feature](?template=feature_template.md)
- [Bugfix](?template=bugfix_template.md)
=> fix: nextjs flickering

apps/docs/src/pages/design/theming.mdx, examples/create-next-app/pages/_app.tsx, packages/react-compass/src/theme/index.ts, packages/react-compass/src/theme/theme.ts, packages/react-compass/src/theme/useColors.ts
- [Feature](?template=feature_template.md)
- [Bugfix](?template=bugfix_template.md)
=> feat: add hook use color

packages/react-compass/src/accordion/accordion-button.styles.ts
The accordion UI is not perfectly aligned
Missing the reset of border-bottom-left and border-bottom-right when accordion is opened
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> fix: accordion ui

apps/docs/src/pages/components/toggle.mdx
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> fix: toggle docs

packages/react-compass/src/upload/upload-drag-and-drop/index.styles.ts, packages/react-compass/src/upload/upload-drag-and-drop/index.tsx, packages/react-compass/src/upload/upload.stories.tsx
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> Fix: Add type button to upload

packages/react-compass/src/textfield/textfield.stories.tsx, packages/react-compass/src/textfield/textfield.tsx
A new component named Gutter
**1) Changes**
[Jira link](https://comfortdelgrotaxi.atlassian.net/browse/CDS-352)
**2) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> Fix: onKeyDown triggered twice

packages/react-compass/src/textfield/textfield.tsx
**1) Changes**
**2) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> Fix build error: Export Props from TextField to use another place

apps/docs/src/pages/components/gutter.mdx, apps/docs/src/styles/Home.module.css, packages/react-compass/src/gutter/gutter-content.styles.ts, packages/react-compass/src/gutter/gutter-content.tsx, packages/react-compass/src/gutter/gutter-context.tsx, packages/react-compass/src/gutter/gutter-resizer.styles.tsx, packages/react-compass/src/gutter/gutter-resizer.tsx, packages/react-compass/src/gutter/gutter.stories.tsx, packages/react-compass/src/gutter/gutter.styles.ts, packages/react-compass/src/gutter/gutter.tsx, packages/react-compass/src/gutter/index.ts, packages/react-compass/src/gutter/useResizer.ts, packages/react-compass/src/index.ts
A new component named Gutter
**1) Changes**
[Jira link](https://comfortdelgrotaxi.atlassian.net/browse/CDS-298)
**2) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> feature: create gutter control component

packages/react-compass/src/theme/theme.ts, packages/react-compass/src/theme/useColors.ts
Fix useColors hook support SSR
**1) Changes**
**2) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [feat] useColors hook support ssr

packages/react-compass/src/calendar/components/date-segment.style.ts
Apply theme color to date segment
**1) Changes**
change pure black text color to primary text color
https://comfortdelgrotaxi.atlassian.net/browse/CDS-374
**2) Impact**
All date pickers and date range pickers
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-374] Date input theme text color

packages/react-compass/src/upload/upload-drag-and-drop/index.tsx, packages/react-compass/src/upload/upload.stories.tsx, packages/react-compass/src/upload/upload.tsx
**1) Changes**
**2) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-405] add file type error handling and customErrorMessage prop for Upload

packages/react-compass/src/dropdown/dropdown.stories.tsx, packages/react-compass/src/dropdown/dropdown.tsx, packages/react-compass/src/dropdown/list-box/index.styles.ts, packages/react-compass/src/dropdown/section/index.tsx, packages/react-compass/src/dropdown/section/section.styles.ts, packages/react-compass/src/dropdown/utils.tsx, packages/react-compass/src/multiple-dropdown/list-box/index.tsx, packages/react-compass/src/multiple-dropdown/multiple-dropdown.stories.tsx, packages/react-compass/src/multiple-dropdown/option/index.styles.ts, packages/react-compass/src/multiple-dropdown/option/index.tsx
**1) Changes**
**2) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-404] add prefix to dropdown select and click event to section in multiple-dropdown

packages/react-compass/src/tag-box/tag-box-input.tsx, packages/react-compass/src/tag-box/tag-box-item.tsx, packages/react-compass/src/tag-box/tag-box.styles.ts, packages/react-compass/src/tag-box/tag-box.tsx
**1) Changes**
[CDS-362](https://comfortdelgrotaxi.atlassian.net/browse/CDS-362)
[CDS-350](https://comfortdelgrotaxi.atlassian.net/browse/CDS-350)
- CDS-362: Tagbox input and wrapper
- CDS-350: wrapper
Need to squash commit cuz both of ticket related to wrapper
**2) Impact**
Tagbox input and wrapper
[CDS-362](https://comfortdelgrotaxi.atlassian.net/browse/CDS-362)
[CDS-350](https://comfortdelgrotaxi.atlassian.net/browse/CDS-350)
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element …
```
=> [CDS-362, CDS-350] Tagbox UX improvement - user can click on the box to focus to input field and Tagbox responsive 

apps/docs/src/pages/components/otp-Input.mdx, packages/react-compass/src/otp-input/otpInput.stories.tsx, packages/react-compass/src/otp-input/otpInput.styles.ts
**1) Changes**
* Add 6 characters demo
* Update responsive layout
**2) Impact**
Input will be smaller on small screen
https://comfortdelgrotaxi.atlassian.net/browse/CDS-319 
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-319] Add 6 inputs demo and responsive

packages/react-compass/package.json, packages/react-compass/src/rich-text-editor/rich-text-editor.stories.tsx, packages/react-compass/src/rich-text-editor/rich-text-editor.styles.ts, packages/react-compass/src/rich-text-editor/rich-text-editor.tsx, pnpm-lock.yaml
Add more samples to rich text editor component (default value, placeholder, 
**1) Changes**
[Jira link](https://comfortdelgrotaxi.atlassian.net/browse/CDS-336)
**2) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-336] Rich Text Editor more samples

packages/react-compass/src/dialog/dialog-actions.tsx, packages/react-compass/src/dialog/dialog.stories.tsx, packages/react-compass/src/dialog/dialog.styles.ts
Add responsive to dialog component
**1) Changes**
- Add padding to overlay
- Add max height and overflow
- Add option to display buttons as stack when in mobile size
https://comfortdelgrotaxi.atlassian.net/browse/CDS-335
**2) Impact**
No breaking changes
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-335] Add Dialog responsive

apps/docs/src/styles/global.css, packages/react-compass/src/list/list.stories.tsx, packages/react-compass/src/popover/popover.stories.tsx, packages/react-compass/src/quantity-toggle/quantity-toggle.styles.ts, packages/react-compass/src/searchfield/searchfield.styles.ts, packages/react-compass/src/searchfield/searchfield.tsx, packages/react-compass/src/table-v2/react-table-row.styles.ts, packages/react-compass/src/table-v2/react-table.styles.ts, packages/react-compass/src/table/table.styles.ts, packages/react-compass/src/tabs/tab/index.styles.ts, packages/react-compass/src/tag-box-v2/tag-box-v2.styles.ts, packages/react-compass/src/tag-box/tag-box.styles.ts, packages/react-compass/src/textarea/textarea.styles.ts, packages/react-compass/src/textfield/textfield.styles.ts, packages/react-compass/src/theme/theme.ts, packages/react-compass/src/time-picker/time-picker.styles.ts, packages/react-compass/src/upload-v2/upload.styles.ts, packages/react-compass/src/upload/upload.styles.ts
Add  dark theme for the rest components
**1) Changes**
https://comfortdelgrotaxi.atlassian.net/jira/software/c/projects/CDS/issues/CDS-369
**2) Impact**
=> [CDS-369] Add DarkTheme for the rest components

packages/react-compass/src/sidebar/sidebar.styles.ts
Fix Sidebar wrong position
Sidebar is currently using position absolute, it position will base on parent node's position, and in this case when the user scrolls down, parent node's position is moved too, thus moving the sidebar.
**2) Changes**
By changing the position absolute to position fixed, sidebar's position now will bind to document and will not be moved
https://comfortdelgrotaxi.atlassian.net/browse/CDS-356
**3) Impact**
No impact
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
Your code …
```
=> [CDS-356] Fix Sidebar position

apps/docs/src/components/TimePickerControlled.tsx, apps/docs/src/pages/components/time-picker.mdx
**1) Changes**
**2) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> Add docs .mdx for time-picker

apps/docs/src/components/DatePickers.tsx, apps/docs/src/pages/_app.tsx, apps/docs/src/pages/components/date-picker.mdx, apps/docs/src/pages/components/date-range-picker.mdx, packages/react-compass/src/calendar/calendar-cell.style.ts, packages/react-compass/src/calendar/calendar.tsx, packages/react-compass/src/calendar/components/date-field.style.ts, packages/react-compass/src/date-picker/date-picker.stories.tsx, packages/react-compass/src/date-picker/date-picker.tsx, packages/react-compass/src/date-range-picker/date-range-picker.stories.tsx
Update calendar and other related documents
**1) Changes**
+) Add more examples in ladle
+) Update i18n import guide
https://comfortdelgrotaxi.atlassian.net/browse/CDS-413
**2) Impact**
+) Impact calendar related component in both ladle and docs
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-413] Update calendar and other related documents

apps/docs/src/pages/components/dropdown.mdx, packages/react-compass/src/dropdown/dropdown.stories.tsx, packages/react-compass/src/dropdown/dropdown.tsx, packages/react-compass/src/dropdown/utils.tsx
**1) Changes**
[CDS-417](https://comfortdelgrotaxi.atlassian.net/browse/CDS-417)
**2) Impact**
Only for Dropdown.ComboBox
[CDS-417](https://comfortdelgrotaxi.atlassian.net/browse/CDS-417)
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
[CDS-417]: https://comfortdelgrotaxi.atlassian.net/browse/CDS-417?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CDS-417]: https://comfortdelgrotaxi.atlassian.net/browse/CDS-417?atlOrigin=eyJpIjoiN …
=> [CDS-417] new disable clearable props for combobox

packages/react-compass/src/data-grid/README.md
Create some architecture diagrams and flow charts for DataGrid/Table V2 component
**1) Changes**
+) Add README.md file under /datagrid folder.
https://comfortdelgrotaxi.atlassian.net/browse/CDS-392 
**2) Impact**
+) Impact calendar related component in both ladle and docs
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-392] React compass table v 2 create architecture overview design

packages/react-compass/src/card/card-action.styles.ts, packages/react-compass/src/card/card.styles.ts, packages/react-compass/src/theme/breakpoints.ts
Break when screen size is under 320
**2) Changes**
[CDS-342](https://comfortdelgrotaxi.atlassian.net/browse/CDS-342)
**3) Impact**
Impact to Card Action
[CDS-342](https://comfortdelgrotaxi.atlassian.net/browse/CDS-342)
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
[CDS-342]: https://comfortdelgrotaxi.atlassian.net/browse/CDS-342?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CDS-342]: …
=> [CDS-342] Card actions buttons responsive layout

packages/react-compass/src/popover/index.ts, packages/react-compass/src/popover/popover.stories.tsx, packages/react-compass/src/popover/popover.style.ts, packages/react-compass/src/popover/popover.tsx
**1) Changes**
[](https://comfortdelgrotaxi.atlassian.net/browse/CDS-391)
**2) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-391] improve popover

packages/react-compass/src/alert/alert.styles.ts, packages/react-compass/src/alert/alert.tsx
**1) Changes**
[CDS-340](https://comfortdelgrotaxi.atlassian.net/browse/CDS-340)
**2) Impact**
Alert wrapper
[CDS-340](https://comfortdelgrotaxi.atlassian.net/browse/CDS-340)
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
[CDS-340]: https://comfortdelgrotaxi.atlassian.net/browse/CDS-340?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CDS-340]: https://comfortdelgrotaxi.atlassian.net/browse/CDS-340?atlOrigin=eyJpIjoiNWRkNTljNzYxNj …
=> [CDS-340] Improve Alert responsive layout

packages/react-compass/src/breadcrumbs/breadcrumbs.styles.ts
Missing flex wrap for flex box css
**2) Changes**
[CDS-341](https://comfortdelgrotaxi.atlassian.net/browse/CDS-341)
**3) Impact**
Breadcrumbs wrapper
[CDS-341](https://comfortdelgrotaxi.atlassian.net/browse/CDS-341)
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
[CDS-341]: https://comfortdelgrotaxi.atlassian.net/browse/CDS-341?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CDS-341]: …
=> [CDS-341] Breadcrumbs responsive layout

packages/react-compass/src/video-player/video-player.styles.ts
Video volume controller is to big on mobile -> overlap progress controller
**2) Changes**
[CDS-346](https://comfortdelgrotaxi.atlassian.net/browse/CDS-346)
**3) Impact**
Move volume controller to top by 35%
[CDS-346](https://comfortdelgrotaxi.atlassian.net/browse/CDS-346)
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
[CDS-346]: https://comfortdelgrotaxi.atlassian.net/browse/CDS-346?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0a …
=> [CDS-346] Video responsive layout

apps/docs/src/pages/components/toggle.mdx, packages/react-compass/src/toggle/toggle.stories.tsx, packages/react-compass/src/toggle/toggle.tsx
**1) Changes**
[CDS-418](https://comfortdelgrotaxi.atlassian.net/browse/CDS-418)
**2) Impact**
Toggle component
[CDS-418](https://comfortdelgrotaxi.atlassian.net/browse/CDS-418)
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
[CDS-418]: https://comfortdelgrotaxi.atlassian.net/browse/CDS-418?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CDS-418]: https://comfortdelgrotaxi.atlassian.net/browse/CDS-418?atlOrigin=eyJpIjoiNWRkNTljNzY …
=> [CDS-418] add isReadonly and more docs usage for toggle

apps/docs/src/pages/components/multiple-dropdown.mdx, packages/react-compass/src/multiple-dropdown/multiple-dropdown.stories.tsx, packages/react-compass/src/multiple-dropdown/multiple-dropdown.styles.ts, packages/react-compass/src/multiple-dropdown/multiple-dropdown.tsx, packages/react-compass/src/multiple-dropdown/option/index.styles.ts, packages/react-compass/src/multiple-dropdown/option/index.tsx
**1) Changes**
[CDS-414](https://comfortdelgrotaxi.atlassian.net/browse/CDS-414)
**2) Impact**
Dropdown chips error border
[CDS-414](https://comfortdelgrotaxi.atlassian.net/browse/CDS-414)
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
[CDS-414]: https://comfortdelgrotaxi.atlassian.net/browse/CDS-414?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CDS-414]: https://comfortdelgrotaxi.atlassian.net/browse/CDS-414?atlOrigin=eyJpIjoi …
=> [CDS-414] Error state for multiple-dropdown and its individual chip

apps/docs/src/pages/components/radio.mdx, packages/react-compass/src/radio/radio.styles.ts, packages/react-compass/src/radio/radio.tsx
Radio responsive layout
**1) Changes**
https://comfortdelgrotaxi.atlassian.net/jira/software/c/projects/CDS/issues/CDS-345
**2) Impact**
=> [CDS-345] Radio responsive layout

apps/docs/src/components/DataGrid.tsx, apps/docs/src/pages/components/data-grid.mdx
Create document page for grid data
**1) Changes**
https://comfortdelgrotaxi.atlassian.net/browse/CDS-401
**2) Impact**
=> [CDS-401] Create document page for grid data

apps/docs/src/pages/components/navbar.mdx, packages/react-compass/src/navbar/index.ts, packages/react-compass/src/navbar/navbar-actions.styles.ts, packages/react-compass/src/navbar/navbar-actions.tsx, packages/react-compass/src/navbar/navbar-brand.styles.ts, packages/react-compass/src/navbar/navbar-brand.tsx, packages/react-compass/src/navbar/navbar-links.styles.ts, packages/react-compass/src/navbar/navbar-seperator.style.ts, packages/react-compass/src/navbar/navbar.stories.tsx, packages/react-compass/src/navbar/navbar.styles.ts, packages/react-compass/src/navbar/navbar.tsx
Add responsive to navbar
**1) Changes**
Create new compound components to handle every aspects of navbar like: Links, Action Buttons, Separator
https://comfortdelgrotaxi.atlassian.net/browse/CDS-344
**2) Impact**
No breaking changes, backward compatible
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-302] Add Navbar responsive

apps/docs/src/pages/components/menu-lists.mdx, packages/react-compass/src/menu-list/menu-list-dropdown-header.styles.ts, packages/react-compass/src/menu-list/menu-list-dropdown-header.tsx, packages/react-compass/src/menu-list/menu-list-dropdown-item.styles.ts, packages/react-compass/src/menu-list/menu-list-dropdown-item.tsx, packages/react-compass/src/menu-list/menu-list-dropdown.styles.tsx, packages/react-compass/src/menu-list/menu-list-dropdown.tsx, packages/react-compass/src/menu-list/menu-list.styles.ts
Menu list header cannot be toggled by keyboard
The event used here is onMouseDown, hence user cannot use mobile device or keyboard to interact
**2) Changes**
Remove onMouseDown, use onClick instead
https://comfortdelgrotaxi.atlassian.net/browse/CDS-359
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-359] Fix menu list can not press enter or spacebar to select or expand item

packages/react-compass/src/upload/upload.tsx
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> Fix/delete console.log

packages/react-compass/src/theme/breakpoints.ts, packages/react-compass/src/upload/upload.tsx
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-455] Fix/grid

packages/react-compass/src/accordion/accordion-button.tsx
Accordion button auto submitting when click
Accordion button is type submit
**2) Changes**
Change accordion button type to "button"
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> fix: accordion button type

.github/workflows/release-sit.yml
**1) Changes**
Added new workflow file for SIT
**2) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [Chore] Added new workflow file for SIT - Develop

.github/workflows/release-beta.yml, .github/workflows/release-sit.yml
**1) Changes**
Added new workflow file for SIT
**2) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [Chore] Added new workflow file for SIT - Main

apps/docs/src/components/TagBoxV2.tsx, apps/docs/src/pages/components/tag-box-v2.mdx, apps/docs/src/pages/components/tag-box.mdx, packages/react-compass/src/tag-box-v2/tag-box-v2.stories.tsx, packages/react-compass/src/tag-box-v2/tag-box-v2.styles.ts, packages/react-compass/src/tag-box-v2/tag-box-v2.tsx, packages/react-compass/src/tag-box-v2/types.ts, packages/react-compass/src/tag-box/tag-box.stories.tsx
Add Error state for each item
**1) Changes**
https://comfortdelgrotaxi.atlassian.net/jira/software/c/projects/CDS/issues/CDS-460
**2) Impact**
=> [CDS-460] Add Error state for each item

packages/react-compass/package.json, packages/react-compass/src/portal/index.tsx, packages/react-compass/src/theme/keyframes.ts, packages/react-compass/src/toast/service/toast-container.tsx, packages/react-compass/src/toast/service/toast-context.tsx, packages/react-compass/src/toast/service/toast-item.styles.ts, packages/react-compass/src/toast/service/toast-item.tsx, packages/react-compass/src/toast/toast.stories.tsx, pnpm-lock.yaml
**1) Changes**
**2) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-453] Using createPortal and anchorOrigin prop for ToastContainer

apps/docs/src/components/Sidebar.tsx, apps/docs/src/pages/components/sidebar.mdx, packages/react-compass/src/sidebar/sidebar.stories.tsx
**1) Changes**
[CDS-434](https://comfortdelgrotaxi.atlassian.net/browse/CDS-434)
**2) Impact**
Sidebar ladle and docs
[CDS-434](https://comfortdelgrotaxi.atlassian.net/browse/CDS-434)
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
[CDS-434]: https://comfortdelgrotaxi.atlassian.net/browse/CDS-434?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CDS-434]: https://comfortdelgrotaxi.atlassian.net/browse/CDS-434?atlOrigin=eyJpIjoiNWRkN …
=> [CDS-434] Sidebar should have demo on the right page

packages/react-compass/src/dropdown-new/dropdown-new.tsx
**1) Changes**
**2) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-420] Add allowsCustomValue prop

packages/react-compass/src/dialog/dialog-actions.tsx, packages/react-compass/src/dialog/dialog-trigger.tsx, packages/react-compass/src/modal/modal-trigger.tsx
Wrapping modal/dialog components into Portal. The content will be rendered in the body level
**1) Changes**
**2) Impact**
[CDS-432](https://comfortdelgrotaxi.atlassian.net/browse/CDS-432)
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
[CDS-432]: https://comfortdelgrotaxi.atlassian.net/browse/CDS-432?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CDS-432] use Portal to move dialog modal to body level

apps/docs/src/pages/components/buttons.mdx, packages/react-compass/src/button/button.stories.tsx, packages/react-compass/src/button/button.styles.ts, packages/react-compass/src/button/button.tsx
Add Link button
**1) Changes**
https://comfortdelgrotaxi.atlassian.net/browse/CDS-431
**2) Impact**
=> [CDS-431] Add Link button

apps/docs/src/components/FormLayout.tsx, apps/docs/src/pages/components/form-layout.mdx, packages/react-compass/src/form-layout/FormLayout.stories.tsx, packages/react-compass/src/form-layout/FormLayout.styles.ts, packages/react-compass/src/form-layout/FormLayout.tsx, packages/react-compass/src/form-layout/FormLayoutExplaination.tsx, packages/react-compass/src/form-layout/FormLayoutGroup.tsx, packages/react-compass/src/form-layout/FormLayoutRow.tsx, packages/react-compass/src/form-layout/index.ts, packages/react-compass/src/index.ts
Create a FormLayout component including Rows and Columns to put in form controls.
**1) Changes**
- New FormLayout component.
- Docs for FormLayout.
**2) Impact**
[CDS-366](https://comfortdelgrotaxi.atlassian.net/browse/CDS-366)
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
[CDS-366]: https://comfortdelgrotaxi.atlassian.net/browse/CDS-366?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CDS-366] Creating FormLayout component

apps/docs/src/pages/components/action-bar.mdx, apps/docs/src/styles/global.css, packages/react-compass/src/action-bar/ActionBar.stories.tsx, packages/react-compass/src/action-bar/ActionBar.styles.ts, packages/react-compass/src/action-bar/ActionBar.tsx, packages/react-compass/src/action-bar/ActionBarCenterGroup.tsx, packages/react-compass/src/action-bar/ActionBarLeftGroup.tsx, packages/react-compass/src/action-bar/ActionBarRightGroup.tsx, packages/react-compass/src/action-bar/index.ts, packages/react-compass/src/index.ts
**1) Changes**
* Add new action bar layout component
**2) Impact**
https://comfortdelgrotaxi.atlassian.net/browse/CDS-367
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-367] feature/action-bar

packages/react-compass/src/tag-box/tag-box-item.tsx, packages/react-compass/src/tag-box/tag-box.styles.ts, packages/react-compass/src/tag-box/tag-box.tsx
**1) Changes**
[CDS-429](https://comfortdelgrotaxi.atlassian.net/browse/CDS-429)
**2) Impact**
Item close button now can be focussed by Tab key
[CDS-429](https://comfortdelgrotaxi.atlassian.net/browse/CDS-429)
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
[CDS-429]: https://comfortdelgrotaxi.atlassian.net/browse/CDS-429?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CDS-429]: …
=> [CDS-429] Tag Box handle keyboard events

packages/react-compass/src/tabs/tab/index.styles.ts, packages/react-compass/src/tabs/tab/index.tsx, packages/react-compass/src/tabs/tabs.tsx, packages/react-compass/src/tabs/utils.ts
**1) Changes**
[CDS-424](https://comfortdelgrotaxi.atlassian.net/browse/CDS-424)
**2) Impact**
Tab item wrapper
[CDS-424](https://comfortdelgrotaxi.atlassian.net/browse/CDS-424)
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
[CDS-424]: https://comfortdelgrotaxi.atlassian.net/browse/CDS-424?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CDS-424]: https://comfortdelgrotaxi.atlassian.net/browse/CDS-424?atlOrigin=eyJpIjoiNWRkNTljNzY …
=> [CDS-424] Tab handle keyboard events

packages/react-compass/package.json, packages/react-compass/src/speed-dial/speed-dial-action.tsx, packages/react-compass/src/speed-dial/speed-dial-trigger.tsx, packages/react-compass/src/speed-dial/speed-dial.styles.ts, packages/react-compass/src/speed-dial/speed-dial.tsx, packages/react-compass/src/utils/hooks/index.ts, packages/react-compass/src/utils/hooks/useKeyboardNavigation.tsx, packages/react-compass/src/utils/hooks/useKeyboardNavigationState.ts, packages/react-compass/src/utils/keyboard.enum.ts, pnpm-lock.yaml
Add a11y to speed dial component
**1) Changes**
+) Change speed dial item from div element to button element
+) Add roles to speed dial item
+) Add a hook that helps navigating through the component using arrow keys
https://comfortdelgrotaxi.atlassian.net/browse/CDS-427
**2) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-427] Add accessibility to speed dial

packages/react-compass/package.json
Our current version is  "@react-stately/table": "^3.5.0",
And its latest version is 3.10.0, which conflicts on users' end. Solve this problem by using resolution and peer dependency parameters to lock it at a certain version.
**1) Changes**
Add version 3.9.0 of react-stately/table to `resolutions`
**2) Impact**
[](https://comfortdelgrotaxi.atlassian.net/browse/CDS-456)
=> [CDS-456] Update peer dependency @react-stately/table for table v1

packages/react-compass/src/popover/README.md
Create Popover document
**1) Changes**
Create README.md in popover folder
https://comfortdelgrotaxi.atlassian.net/browse/CDS-439
**2) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-439] Create popover docs

packages/react-compass/src/rich-text-editor/README.md
Create architecture design document for RichTextEditor component.
**1) Changes**
Confluence page: https://comfortdelgrotaxi.atlassian.net/wiki/spaces/CDG1/pages/1115115933/Rich+Text+Editor
**2) Impact**
https://comfortdelgrotaxi.atlassian.net/browse/CDS-440
=> [CDS-440] Rich text editor architecture design document

apps/docs/src/components/TextField.tsx, apps/docs/src/pages/components/textField.mdx, packages/react-compass/src/textfield/textfield.stories.tsx
**1) Changes**
**2) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> Chore: Add controlled textfield to docs

apps/docs/src/components/Dialog.tsx, apps/docs/src/components/Modal.tsx, apps/docs/src/pages/components/dialog.mdx, apps/docs/src/pages/components/modal.mdx, packages/react-compass/src/button/button.styles.ts, packages/react-compass/src/dialog/dialog-trigger.tsx, packages/react-compass/src/dialog/dialog.stories.tsx, packages/react-compass/src/dialog/dialog.styles.ts, packages/react-compass/src/dialog/dialog.tsx, packages/react-compass/src/modal/modal-closeIcon.tsx, packages/react-compass/src/modal/modal-trigger.tsx, packages/react-compass/src/modal/modal.stories.tsx, packages/react-compass/src/modal/modal.styles.ts, packages/react-compass/src/modal/modal.tsx
**1) Changes**
**2) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-334] Fix/focus handler for modal dialog

packages/react-compass/src/date-picker/README.md, packages/react-compass/src/date-range-picker/README.md
Create Datepicker document
**1) Changes**
Add README.md to datepicker folder
https://comfortdelgrotaxi.atlassian.net/browse/CDS-438
**2) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-438] Datepicker document

apps/docs/src/pages/components/date-range-picker.mdx, apps/docs/src/pages/components/range-calendar.mdx, packages/react-compass/src/calendar/hooks/useSlotId.ts, packages/react-compass/src/date-range-picker/date-range-picker.stories.tsx, packages/react-compass/src/date-range-picker/date-range-picker.style.ts, packages/react-compass/src/date-range-picker/date-range-picker.tsx, packages/react-compass/src/range-calendar/range-calendar.tsx, packages/react-compass/src/utils/use-media-query.ts
Make date range calendar responsive, using this new design [figma](https://www.figma.com/file/JSiK3cmMmxTt8qhR3dty8t/Workbench-Design-System?type=design&node-id=11858-136579&mode=design&t=GFTp4cKtpFJtA2ut-4)
**1) Changes**
+ Add breakpoint of 768px to date range picker 
+ Apply responsive design
+ Add prop to Range calendar to make it renders 1 calendar only
https://comfortdelgrotaxi.atlassian.net/browse/CDS-333
**2) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-333] add date range picker responsive

packages/react-compass/src/checkbox/checkbox.stories.tsx, packages/react-compass/src/checkbox/checkbox.styles.ts, packages/react-compass/src/checkbox/checkbox.tsx
Styling focusing state for checkbox.
**1) Changes**
Add styles to css.
https://comfortdelgrotaxi.atlassian.net/browse/CDS-433
**2) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-433] Checkbox focusing state

packages/react-compass/src/upload/upload.styles.ts, packages/react-compass/src/upload/upload.tsx
Improve file upload component a11y, user now can use tab key to navigate the component
**1) Changes**
+ Change browse file div element to button element
+ Add border color when component is focused
https://comfortdelgrotaxi.atlassian.net/browse/CDS-426
**2) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-426] Add accessibility to file upload

packages/react-compass/src/upload/upload-drag-and-drop/index.tsx, pnpm-lock.yaml
**1) Changes**
**2) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> Fix: delete-redundant-console.log

apps/docs-v2/README.md
**1) Changes**
**2) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-506] feat update readme docs v2

apps/docs/src/components/TableV2.tsx, apps/docs/src/pages/components/table-v2.mdx, packages/react-compass/src/data-grid/data-grid-cell.styles.ts, packages/react-compass/src/data-grid/data-grid-column-header.styles.ts, packages/react-compass/src/data-grid/data-grid-row.styles.ts, packages/react-compass/src/data-grid/data-grid-row.tsx, packages/react-compass/src/data-grid/data-grid.tsx, packages/react-compass/src/index.ts, packages/react-compass/src/table-v2/index.ts, packages/react-compass/src/table-v2/makeData.ts, packages/react-compass/src/table-v2/react-table.tsx, packages/react-compass/src/table-v2/table-v2.stories.tsx
**1) Changes**
- New props `renderRowSubComponent` for table.
- Updated docs.
**2) Impact**
[](https://comfortdelgrotaxi.atlassian.net/browse/CDS-469)
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-469] expandable table section

packages/react-compass/src/spinner/spinner.styles.ts, packages/react-compass/src/spinner/spinner.tsx
Current shows outline when focussed
**2) Changes**
[CDS-468](https://comfortdelgrotaxi.atlassian.net/browse/CDS-468)
**3) Impact**
Set tab index -1 and disable border and outline
[CDS-468](https://comfortdelgrotaxi.atlassian.net/browse/CDS-468)
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
[CDS-468]: https://comfortdelgrotaxi.atlassian.net/browse/CDS-468?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …
=> [CDS-468]][Defect] Loading indicator should not shows outline border

apps/docs/src/components/TagBox.tsx, apps/docs/src/pages/components/tag-box.mdx, packages/react-compass/src/tag-box/tag-box-item.tsx, packages/react-compass/src/tag-box/tag-box.stories.tsx, packages/react-compass/src/tag-box/tag-box.styles.ts, packages/react-compass/src/tag-box/tag-box.tsx
CRUD event only log to console 
**2) Changes**
[CDS-473](https://comfortdelgrotaxi.atlassian.net/browse/CDS-473)
**3) Impact**
Add react state and CRUD function
[CDS-473](https://comfortdelgrotaxi.atlassian.net/browse/CDS-473)
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
[CDS-473]: https://comfortdelgrotaxi.atlassian.net/browse/CDS-473?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CDS-473]: …
=> [CDS-473][Defect] TagBox documents cannot be added or deleted

packages/react-compass/src/chip/chip.tsx, packages/react-compass/src/multiple-dropdown/multiple-dropdown.tsx
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> Prevent toggle dropdown when close to close button

packages/react-compass/src/toggle/toggle.tsx
onChange wrapped by useEffect
**2) Changes**
**3) Impact**
move onChange to trigger function
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CHORE] toggle onChange trigger each time rerender

packages/react-compass/src/button/button.stories.tsx, packages/react-compass/src/button/button.styles.ts, packages/react-compass/src/button/button.tsx, packages/react-compass/src/timeline/timeline.styles.ts
Button content is not centered when its width is a fixed number
**1) Changes**
https://comfortdelgrotaxi.atlassian.net/browse/CDS-475
**2) Impact**
=> [CDS-475][bug] Button content is not centered when its width is a fixed number

apps/docs/src/pages/components/popover.mdx, packages/react-compass/src/popover/popover.tsx, packages/react-compass/src/radio/radio-group.tsx, packages/react-compass/src/radio/radio.stories.tsx, packages/react-compass/src/sidebar/sidebar.tsx
**1) Changes**
**2) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=>  Fix bugs in radio/sidebar and add isFloatingPortal prop to popover

apps/docs-v2/components/home/Banner.tsx, apps/docs-v2/components/home/Hero.tsx, apps/docs-v2/components/home/Introduction/index.tsx, apps/docs-v2/components/home/Introduction/item.tsx, apps/docs-v2/components/home/ReactCompass/CoreShowcase.tsx, apps/docs-v2/components/home/ReactCompass/PreflightComponent.tsx, apps/docs-v2/components/home/ReactCompass/ShowcaseContainer.tsx, apps/docs-v2/components/home/ReactCompass/ShowcaseDemo.tsx, apps/docs-v2/components/home/ReactCompass/index.tsx, apps/docs-v2/components/home/ReadyToUse.tsx, apps/docs-v2/components/layouts/Container.tsx, apps/docs-v2/pages/global.css, apps/docs-v2/pages/index.tsx
**1) Changes**
* Update new home page layout
**2) Impact**
https://comfortdelgrotaxi.atlassian.net/browse/CDS-465
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-465] feature home page content and responsive layout

apps/docs-v2/components/common/CommonHeader.tsx
CommonHeader's Breadcrumbs Item is missing href
**2) Changes**
[CDS-515](https://comfortdelgrotaxi.atlassian.net/browse/CDS-515)
**3) Impact**
Added href for Breadcrumbs Item
[CDS-515](https://comfortdelgrotaxi.atlassian.net/browse/CDS-515)
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
[CDS-515]: https://comfortdelgrotaxi.atlassian.net/browse/CDS-515?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CDS-515]: …
=> [CDS-515] Breadcrumb make app crashed when click on it 

packages/react-compass/src/list/drag-and-drop/index.styles.ts, packages/react-compass/src/list/drag-and-drop/item/index.tsx, packages/react-compass/src/list/drag-and-drop/item/outlet.tsx, packages/react-compass/src/list/list-card.tsx, packages/react-compass/src/list/list.stories.tsx
scan and enhance accessibility to List View
**1) Changes**
- Add aria attributes
- Add outline color when focus
- Improve examples UI
https://comfortdelgrotaxi.atlassian.net/browse/CDS-498
**2) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-498] List View scan and enhance accessibility

packages/react-compass/src/tabs/tab-panel/index.tsx, packages/react-compass/src/tabs/tab.stories.tsx, packages/react-compass/src/tabs/tab/index.styles.ts, packages/react-compass/src/tabs/tab/index.tsx, packages/react-compass/src/tabs/tabs.tsx, packages/react-compass/src/utils/hooks/useKeyboardNavigation.tsx
Apply accessibility to tab 
**1) Changes**
- Add aria attributes
- Add roles
- Add outline color when focus
- Add keyboard navigation, will now able to use arrow key to navigate 
https://comfortdelgrotaxi.atlassian.net/browse/CDS-505
**2) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-505] feature: apply accessibility to tab

apps/docs/src/pages/components/navbar.mdx, packages/react-compass/src/navbar/index.ts, packages/react-compass/src/navbar/navbar-links.styles.ts, packages/react-compass/src/navbar/navbar-links.tsx, packages/react-compass/src/navbar/navbar.stories.tsx, packages/react-compass/src/navbar/navbar.styles.ts, packages/react-compass/src/navbar/navbar.tsx
Add navbar accessibility
**1) Changes**
- Use link buttons in examples
- Use ul, li tag to handle links
- Add role navigation
https://comfortdelgrotaxi.atlassian.net/browse/CDS-500
**2) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-500] feature: apply accessibility to navbar

packages/react-compass/src/pagination/pagination.tsx
**1) Changes**
Add aria-label, aria-current to items in the pagination bar.
**2) Impact**
https://design-system.w3.org/components/pagination.html
[CDS-474](https://comfortdelgrotaxi.atlassian.net/browse/CDS-501)
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
[CDS-474]: https://comfortdelgrotaxi.atlassian.net/browse/CDS-474?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CDS-474]: …
=> [CDS-474] provide accessibility for pagination

packages/react-compass/src/quantity-toggle/utils/useNumberField/index.ts
**1) Changes**
Remove accessibilty from buttons
**2) Impact**
https://react-spectrum.adobe.com/react-aria/NumberField.html
[CDS-502](https://comfortdelgrotaxi.atlassian.net/browse/CDS-502)
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
[CDS-502]: https://comfortdelgrotaxi.atlassian.net/browse/CDS-502?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CDS-502] Accessibility for quantity toggle

packages/react-compass/src/radio/radio-group.tsx, packages/react-compass/src/radio/radio.stories.tsx, packages/react-compass/src/radio/radio.styles.ts, packages/react-compass/src/radio/radio.tsx
Radio Group - Scan and update accessibility suggested by w3c
link : https://www.w3.org/WAI/ARIA/apg/patterns/radio/examples/radio/
**1) Changes**
https://comfortdelgrotaxi.atlassian.net/browse/CDS-503
**2) Impact**
=> [CDS-503] Radio Group - Scan and update accessibility suggested by w3c

packages/react-compass/src/checkbox/checkbox.tsx
Checkbox - Scan and update accessibility suggested by w3c
link: https://www.w3.org/WAI/ARIA/apg/patterns/checkbox/examples/checkbox/
**1) Changes**
https://comfortdelgrotaxi.atlassian.net/browse/CDS-494
**2) Impact**
=> [CDS-494] Checkbox - Scan and update accessibility suggested by w3c

packages/react-compass/src/link/link.styles.ts, packages/react-compass/src/link/link.tsx
Link - Scan and update accessibility suggested by w3c
link: https://www.w3.org/WAI/ARIA/apg/patterns/link/examples/link/
**1) Changes**
https://comfortdelgrotaxi.atlassian.net/browse/CDS-497
**2) Impact**
=> [CDS-497] Link - Scan and update accessibility suggested by w3c 

packages/react-compass/src/chart/README.md
In that file we will need some of: Flow chart, sequence diagram, uml diagram… to let other understand how our component works
**1) Changes**
https://comfortdelgrotaxi.atlassian.net/browse/CDS-441
**2) Impact**
=> [CDS-441] Create Chart architecture design document

packages/react-compass/src/modal/readme.md
**1) Changes**
**2) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-412} [react][design] Create architecture design document for Dialog / Modal

packages/react-compass/src/auto-complete/autoComplete.tsx
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-522] Fix debounce and unable to input the same value

packages/react-compass/src/auto-complete/autoComplete.stories.tsx, packages/react-compass/src/auto-complete/autoComplete.styles.tsx, packages/react-compass/src/auto-complete/autoComplete.tsx
**1) Changes**
**2) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-523] [CDS-489] add onLoadMore and accessibility for autocomplete

packages/react-compass/src/searchfield/searchfield.styles.ts
hot fix syntax css
**1) Changes**
**2) Impact**
=> [yagin][hot fix syntax css]

apps/docs/src/pages/components/dropdown.mdx, apps/docs/src/pages/components/multiple-dropdown.mdx, packages/react-compass/src/dropdown/dropdown-context.ts, packages/react-compass/src/dropdown/dropdown-list.tsx, packages/react-compass/src/dropdown/dropdown.stories.tsx, packages/react-compass/src/dropdown/dropdown.tsx, packages/react-compass/src/multiple-dropdown/multiple-dropdown-context.ts, packages/react-compass/src/multiple-dropdown/multiple-dropdown-item.tsx, packages/react-compass/src/multiple-dropdown/multiple-dropdown-list.tsx, packages/react-compass/src/multiple-dropdown/multiple-dropdown.tsx
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> Add prop isLoadingMore for Dropdown

packages/react-compass/src/button/button.stories.tsx, packages/react-compass/src/button/button.tsx
**1) Changes**
**2) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-507] [CDS-491] add accessibility to button and disable its events on disabled and loading

apps/docs/src/components/LayoutAlignment.tsx, apps/docs/src/pages/layouts/layouts.mdx, apps/docs/src/styles/global.css, packages/react-compass/src/layouts/Layout.tsx
**1) Changes**
Update demo layout for better preview
**2) Impact**
https://comfortdelgrotaxi.atlassian.net/browse/CDS-443
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-443] Update Layout demo

apps/docs/src/pages/components/dropdown.mdx, apps/docs/src/pages/components/multiple-dropdown.mdx, apps/docs/src/styles/Home.module.css, packages/react-compass/src/dropdown-menu/dropdown-menu.stories.tsx, packages/react-compass/src/dropdown/dropdown.stories.tsx, packages/react-compass/src/dropdown/dropdown.tsx, packages/react-compass/src/multiple-dropdown/multiple-dropdown.stories.tsx, packages/react-compass/src/multiple-dropdown/multiple-dropdown.tsx
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> Add popoverCSS Dropdown & MultipleDropdown

apps/docs/src/pages/components/transitions.mdx, packages/react-compass/src/transitions/transitions.stories.tsx, packages/react-compass/src/transitions/transitions.styles.ts, packages/react-compass/src/transitions/transitions.tsx
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-508] fix Transitions' bugs and add more section to its docs

apps/docs/src/pages/components/dropdown.mdx, packages/react-compass/src/dropdown/dropdown.styles.ts, packages/react-compass/src/multiple-dropdown/multiple-dropdown.styles.ts, packages/react-compass/src/theme/theme.ts
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> Add darker color when focus field errored

packages/react-compass/src/dropdown/dropdown-item.tsx, packages/react-compass/src/dropdown/dropdown.stories.tsx, packages/react-compass/src/dropdown/dropdown.tsx
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> Fix bug height of Dropdown for number of rows

packages/react-compass/src/dropdown/dropdown.tsx, packages/react-compass/src/multiple-dropdown/multiple-dropdown.stories.tsx, packages/react-compass/src/multiple-dropdown/multiple-dropdown.tsx
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> Fix bug close Popover after selecting item by 'Enter' key

apps/docs-v2/components/layouts/DocsAppFrame.tsx, apps/docs-v2/constants/routes.ts, apps/docs-v2/data/components/accordions/AccordionsBasic.tsx, apps/docs-v2/data/components/accordions/AccordionsBasic.tsx.preview, apps/docs-v2/data/components/accordions/AccordionsControlled.tsx, apps/docs-v2/data/components/accordions/AccordionsControlled.tsx.preview, apps/docs-v2/data/components/accordions/AccordionsCustom.tsx, apps/docs-v2/data/components/accordions/AccordionsExpandDefault.tsx, apps/docs-v2/data/components/accordions/AccordionsExpandDefault.tsx.preview, apps/docs-v2/data/components/accordions/AccordionsTable.tsx, apps/docs-v2/data/components/accordions/accordions.md, apps/docs-v2/pages/components/accordions.tsx
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> Add accordions to docs v2

apps/docs-v2/babel.config.js, apps/docs-v2/components/common/DemoEditor.tsx, apps/docs-v2/components/common/MarkdownElement.tsx, apps/docs-v2/components/layouts/DocsAppToc.tsx, apps/docs-v2/hooks/index.ts, apps/docs-v2/hooks/useMediaQuery.ts, apps/docs-v2/pages/global.css, apps/docs-v2/public/static/styles/prism-okaidia.css
- Update color for light mode of markdown
**2) Screenshot**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> Update color for light mode of markdown

packages/react-compass/src/typography/header/index.tsx
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> fix: typo header tag

apps/docs-v2/components/layouts/AppHeader.tsx, packages/react-compass/src/slider/slider.tsx
hotfix
**1) Changes**
https://comfortdelgrotaxi.atlassian.net/browse/CDS-756
**2) Impact**
=> [CDS-756] fix export navbar

packages/react-compass/src/drawer/drawer-expander.tsx, packages/react-compass/src/drawer/drawer-footer.tsx, packages/react-compass/src/drawer/drawer-header.tsx, packages/react-compass/src/drawer/drawer.stories.tsx, packages/react-compass/src/drawer/drawer.styles.ts, packages/react-compass/src/drawer/drawer.tsx, packages/react-compass/src/drawer/index.ts, packages/react-compass/src/drawer/types.ts, packages/react-compass/src/index.ts, packages/react-compass/src/utils/hooks/index.ts, packages/react-compass/src/utils/hooks/useDrag.tsx
**1) Changes**
Add Drawer component for the H5 project.
**2) Impact**
No
**3) Notes**
The H5 variant needs JS to update inline styles (`height`) for the purpose of resizing the drawer itself according to the user drag actions. So technically, this PR doesn't satisfy No. 3 of the checklist below.
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [NGPDCP-2599 & NGPDCP-2600] Drawer component - normal and H5 variants

packages/react-compass/src/sub-header/index.ts, packages/react-compass/src/sub-header/sub-header-body.style.ts, packages/react-compass/src/sub-header/sub-header-body.tsx, packages/react-compass/src/sub-header/sub-header-description.style.ts, packages/react-compass/src/sub-header/sub-header-description.tsx, packages/react-compass/src/sub-header/sub-header-header.style.ts, packages/react-compass/src/sub-header/sub-header-image.style.ts, packages/react-compass/src/sub-header/sub-header-image.tsx, packages/react-compass/src/sub-header/sub-header-title.style.ts, packages/react-compass/src/sub-header/sub-header-title.tsx, packages/react-compass/src/sub-header/sub-header.stories.tsx, packages/react-compass/src/sub-header/sub-header.style.ts, packages/react-compass/src/sub-header/sub-header.tsx
- Add new variant sub header component for h5
**1) Screenshot
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [NGPDCP-2594] Add new variant sub header component for h5

packages/react-compass/src/checkbox/checkbox.stories.tsx, packages/react-compass/src/checkbox/checkbox.styles.ts, packages/react-compass/src/checkbox/checkbox.tsx
**1) Changes**
**2) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [NGPDCP-2821] H5 checkbox new variant

packages/react-compass/src/button/button.stories.tsx, packages/react-compass/src/button/button.styles.ts, packages/react-compass/src/theme/theme.ts
Update button component for h5
**1) Screen shot
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [NGPDCP-2596] Update button component for h5

packages/react-compass/src/theme/theme.ts, packages/react-compass/src/toggle/toggle.stories.tsx, packages/react-compass/src/toggle/toggle.styles.ts, packages/react-compass/src/toggle/toggle.tsx
**1) Screenshot
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [NGPDCP-2822] Toggle H5 variant

packages/react-compass/src/drawer/drawer.styles.ts, packages/react-compass/src/drawer/drawer.tsx, packages/react-compass/src/utils/hooks/useDrag.tsx
Use `document` as a hooks dependency.
**2) Changes**
**3) Impact**
Drawer component
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> fix: Drawer

apps/docs-v2/components/common/MarkdownElement.tsx, apps/docs-v2/components/header/ThemeModeToggle.tsx, apps/docs-v2/components/layouts/AppHeader.tsx, apps/docs-v2/components/layouts/AppNavbarMobile.tsx, apps/docs-v2/components/layouts/AppSearch.tsx, apps/docs-v2/components/layouts/DocsAppFrame.tsx, apps/docs-v2/components/layouts/DocsAppLayout.tsx, apps/docs-v2/components/layouts/DocsAppSideNav.tsx, apps/docs-v2/components/layouts/DocsAppSideNavMobile.tsx, apps/docs-v2/package.json, apps/docs-v2/pages/global.css, packages/react-compass/src/drawer/drawer.tsx
**1) Screen shot**
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-769] Handle responsive for side nav

packages/react-compass/src/radio/radio.styles.ts
fix Radio wrong style
**1) Changes**
https://comfortdelgrotaxi.atlassian.net/browse/CDS-776
**2) Impact**
=> [CDS-776] Radio wrong style

packages/react-compass/src/confirm-pickup/confirm-pickup.tsx, packages/react-compass/src/toggle/toggle.tsx
Fix build with type error
**1) Screenshot
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> Fix build h5

pnpm-lock.yaml
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> Hotfix: Update pnpm-lock.yaml

apps/docs-v2/components/common/Demo.tsx, apps/docs-v2/components/common/DemoToolbar.tsx, apps/docs-v2/components/home/Introduction/index.tsx, apps/docs-v2/components/home/Introduction/item.tsx, apps/docs-v2/components/home/ReactCompass/ShowcaseContainer.tsx, apps/docs-v2/components/home/ReactCompass/index.tsx, apps/docs-v2/components/layouts/AppSearch.tsx, apps/docs-v2/components/layouts/DocsAppSideNav.tsx, apps/docs-v2/constants/routes.ts, apps/docs-v2/pages/foundation/overview.tsx, apps/docs-v2/pages/global.css, apps/docs-v2/types/common.ts, apps/docs-v2/utils/index.ts, apps/docs-v2/utils/search.ts
Handle search modal for docs v2
**1) Screenshot**
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-768] Update docs search

packages/react-compass/package.json, packages/react-compass/src/utils/descendant/create-context.ts, packages/react-compass/src/utils/descendant/descendant.ts, packages/react-compass/src/utils/descendant/index.ts, packages/react-compass/src/utils/descendant/use-descendant.ts, packages/react-compass/src/utils/descendant/utils.ts, packages/react-compass/src/utils/hooks/useKeyboardNavigation.tsx, packages/react-compass/src/utils/hooks/useKeyboardNavigationState.ts, pnpm-lock.yaml
- @chakra-ui causing deps conflict
**2) Changes**
- Remove @chakra-ui/descendant and replace it with vanilla js
https://comfortdelgrotaxi.atlassian.net/browse/CDS-766
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-766] Remove @chakra-ui and replace it with vanilla js

packages/react-compass/src/transitions/transitions.styles.ts
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> fix: scroll sidenav

packages/react-compass/src/divider/divider.tsx
Divider is missing attribute props
**2) Changes**
[CDS-731](https://comfortdelgrotaxi.atlassian.net/browse/CDS-731)
**3) Impact**
Extend div props attributes to divider props
[CDS-731](https://comfortdelgrotaxi.atlassian.net/browse/CDS-731)
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
[CDS-731]: https://comfortdelgrotaxi.atlassian.net/browse/CDS-731?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CDS-731]: …
=> [CDS-731] Divider - Missing aria attribute props

packages/react-compass/src/wizard/wizard.tsx
Wizard is missing attribute props
**2) Changes**
[CDS-734](https://comfortdelgrotaxi.atlassian.net/browse/CDS-734)
**3) Impact**
Extend div props attributes to wizard props
[CDS-734](https://comfortdelgrotaxi.atlassian.net/browse/CDS-734)
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
[CDS-731]: https://comfortdelgrotaxi.atlassian.net/browse/CDS-731?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CDS-731]: …
=> [CDS-734] Wizard - Missing aria attribute props

apps/docs-v2/constants/routes.ts, apps/docs-v2/data/components/slide-action/SlideAction.tsx, apps/docs-v2/data/components/slide-action/SlideAction.tsx.preview, apps/docs-v2/data/components/slide-action/SlideActionBehavior.tsx, apps/docs-v2/data/components/slide-action/SlideActionBehavior.tsx.preview, apps/docs-v2/data/components/slide-action/SlideActionIcon.tsx, apps/docs-v2/data/components/slide-action/SlideActionIcon.tsx.preview, apps/docs-v2/data/components/slide-action/SlideColorful.tsx, apps/docs-v2/data/components/slide-action/SlideColorful.tsx.preview, apps/docs-v2/data/components/slide-action/SlideCompact.tsx, apps/docs-v2/data/components/slide-action/SlideCompact.tsx.preview, apps/docs-v2/data/components/slide-action/SlideEffect.tsx, apps/docs-v2/data/components/slide-action/SlideEffect.tsx.preview, apps/docs-v2/data/components/slide-action/slide-action.md, apps/docs-v2/pages/components/slide-action.tsx, packages/react-compass/src/drawer/drawer-expander.tsx, packages/react-compass/src/drawer/drawer.tsx, packages/react-compass/src/index.ts, packages/react-compass/src/slide-action/index.ts, packages/react-compass/src/slide-action/slide-action.const.ts, packages/react-compass/src/slide-action/slide-action.stories.tsx, packages/react-compass/src/slide-action/slide-action.styles.ts, packages/react-compass/src/slide-action/slide-action.tsx, packages/react-compass/src/slide-action/slide-action.types.ts, packages/react-compass/src/slide-action/slide-dragger.tsx, packages/react-compass/src/utils/hooks/useDrag.tsx
**1) Changes**
Add Slide action/Swiper component for H5 project.
**2) Impact**
the `useDrag` hooks
**3) UI Preview**
[NGPDCP-2927](https://comfortdelgrotaxi.atlassian.net/browse/NGPDCP-2927)
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
[NGPDCP-2927]: https://comfortdelgrotaxi.atlassian.net/browse/NGPDCP-2927?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [NGPDCP-2927] Slide action/Swiper component

apps/docs-v2/data/components/drawer/DrawerH5.tsx, packages/react-compass/src/radio/radio.tsx
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [NGPDCP-2926] Add example dropdown using modal and drawer

packages/react-compass/src/time-picker/time-picker-dropdown-item.tsx, packages/react-compass/src/time-picker/time-picker-dropdown.tsx, packages/react-compass/src/time-picker/time-picker.styles.ts, packages/react-compass/src/time-picker/time-picker.tsx
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-809] Timepicker keyboard support

apps/docs-v2/data/components/tabs/TabsH5.tsx, apps/docs-v2/data/components/tabs/TabsH5.tsx.preview, apps/docs-v2/data/components/tabs/tabs.md, packages/react-compass/src/tabs/tab-panel/index.styles.ts, packages/react-compass/src/tabs/tab.stories.tsx, packages/react-compass/src/tabs/tab/index.styles.ts, packages/react-compass/src/tabs/tabs.styles.ts, packages/react-compass/src/tabs/utils.ts
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [NGPDCP-2904] Add tab component for h5

apps/docs-v2/data/components/multiple-dropdown/multiple-dropdown.md
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> fix: multiple dropdown in docs

packages/react-compass/src/subBanner/subBanner.styles.ts
[CDS-701](https://comfortdelgrotaxi.atlassian.net/browse/CDS-701)
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
[CDS-701]: https://comfortdelgrotaxi.atlassian.net/browse/CDS-701?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CDS-701] Sub Banner - spacing

packages/react-compass/src/banner/banner.styles.ts
[CDS-698](https://comfortdelgrotaxi.atlassian.net/browse/CDS-698)
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
[CDS-698]: https://comfortdelgrotaxi.atlassian.net/browse/CDS-698?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CDS-698] Banner - content spacing

packages/react-compass/src/upload/upload-drag-and-drop/index.styles.ts
[CDS-794](https://comfortdelgrotaxi.atlassian.net/browse/CDS-794)
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
[CDS-794]: https://comfortdelgrotaxi.atlassian.net/browse/CDS-794?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CDS-794] Drag&Drop upload component - styling

packages/react-compass/src/upload/upload.styles.ts
[CDS-793](https://comfortdelgrotaxi.atlassian.net/browse/CDS-793)
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
[CDS-793]: https://comfortdelgrotaxi.atlassian.net/browse/CDS-793?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CDS-793] Upload component - disabled styling

packages/react-compass/src/upload/upload.styles.ts
[CDS-792](https://comfortdelgrotaxi.atlassian.net/browse/CDS-792)
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
[CDS-792]: https://comfortdelgrotaxi.atlassian.net/browse/CDS-792?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CDS-792] Upload component - font-size

apps/docs-v2/data/components/dropdown/dropdown.md, apps/docs-v2/data/components/multiple-dropdown/multiple-dropdown.md, packages/react-compass/src/dropdown/dropdown.stories.tsx, packages/react-compass/src/dropdown/dropdown.tsx
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> Fix bug disableClearable = false to allow clear data

packages/react-compass/src/pagination/pagination.styles.ts, packages/react-compass/src/pagination/pagination.tsx
Pagination skipping foward button not matching the design
**1) Changes**
https://comfortdelgrotaxi.atlassian.net/browse/CDS-715
**2) Impact**
=> [CDS-715] Pagination skipping foward button not matching the design

apps/docs-v2/data/components/modal/ModalH5.tsx, apps/docs-v2/data/components/modal/ModalH5.tsx.preview, apps/docs-v2/data/components/modal/modal.md, packages/react-compass/src/modal/modal-description.tsx, packages/react-compass/src/modal/modal-title.tsx, packages/react-compass/src/modal/modal.stories.tsx, packages/react-compass/src/modal/modal.styles.ts, packages/react-compass/src/modal/modal.tsx
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [NGPDCP-2920] Add modal for h5

packages/react-compass/src/badge/badge.stories.tsx, packages/react-compass/src/badge/badge.styles.ts
**2) Changes**
https://comfortdelgrotaxi.atlassian.net/browse/CDS-687
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-687] add sizes variant for badge

packages/react-compass/src/action-bar/ActionBar.styles.ts
Miss matching column gap with Figma
**2) Changes**
Change gap value
**3) Impact**
https://comfortdelgrotaxi.atlassian.net/browse/CDS-697
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-697] Fix for actionbar gap

packages/react-compass/src/link/link.stories.tsx, packages/react-compass/src/link/link.styles.ts
Link - Consider styles of link with Figma
**1) Changes**
https://comfortdelgrotaxi.atlassian.net/browse/CDS-758
**2) Impact**
=> [CDS-699] Link - Consider styles of link with Figma

apps/docs/src/components/FormLayout.tsx, apps/docs/src/pages/layouts/form-layout.mdx, packages/react-compass/src/form-layout/FormLayout.stories.tsx, packages/react-compass/src/form-layout/FormLayout.styles.ts, packages/react-compass/src/form-layout/FormLayoutRow.tsx
Does not support user to config responsive mode
**2) Changes**
Add option to let form row displays as 1 single column
**3) Impact**
https://comfortdelgrotaxi.atlassian.net/browse/CDS-742
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-742] Fix/form layout breakline

apps/docs-v2/data/components/button/button.md, apps/docs/src/pages/components/buttons.mdx, packages/react-compass/src/button/button.stories.tsx, packages/react-compass/src/button/button.styles.ts, packages/react-compass/src/button/button.tsx
Button - There's no square icon button
**1) Changes**
https://comfortdelgrotaxi.atlassian.net/browse/CDS-711
**2) Impact**
=> [CDS-711]Button - There's no square icon button

packages/react-compass/src/badge/badge.stories.tsx, packages/react-compass/src/badge/badge.styles.ts, packages/react-compass/src/theme/theme.ts
**2) Changes**
[](https://comfortdelgrotaxi.atlassian.net/browse/CDS-685)
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-685] react badge warning background and text colors

packages/react-compass/src/carousel/carousel-slider.tsx
We didn't handle the resize event to update slide position
**2) Changes**
* Listen to window resize and update slide position
* Convert function to get slide width to a constant
**3) Impact**
https://comfortdelgrotaxi.atlassian.net/browse/CDS-729
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-729] Carousel updates size when user resize window

.changeset/small-mails-attack.md, apps/docs/package.json, pnpm-lock.yaml
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> New release

apps/docs/package.json
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> Add next export

apps/docs/data/components/page-header/PageHeader.tsx, apps/docs/next.config.js, apps/docs/nextConfigDocsInfra.js
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> fix: build

.github/workflows/deploy-site.yml
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> Fix deploy-site.yml

packages/react-compass/src/transitions/transitions.styles.ts
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> fix: transition

apps/docs/pages/compass-design.tsx
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> add: compass design page

apps/docs/components/common/Head.tsx, apps/docs/components/home/Banner.tsx, apps/docs/components/home/Introduction/index.tsx, apps/docs/components/home/ReactCompass/index.tsx, apps/docs/components/home/ReadyToUse.tsx, apps/docs/components/products/ProductsBackground.tsx, apps/docs/pages/_app.tsx, apps/docs/pages/foundation/overview.tsx, apps/docs/utils/getPathStatic.ts, apps/docs/utils/getStaticPath.ts, apps/docs/utils/index.ts
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> fix: build docs v2

apps/docs/components/common/CommonHeader.tsx, apps/docs/components/layouts/AppHeader.tsx, apps/docs/components/layouts/AppNavbarMobile.tsx
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> fix: show image

apps/docs/data/components/drawer/DrawerCustomize.tsx, apps/docs/data/components/drawer/DrawerH5.tsx, apps/docs/data/components/drawer/DrawerMode.tsx, packages/react-compass/src/drawer/drawer.stories.tsx, packages/react-compass/src/drawer/drawer.styles.ts
Add examples.
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> docs: Drawer - add non-modal examples

packages/react-compass/src/sub-header/sub-header.stories.tsx
[CDS-811](https://comfortdelgrotaxi.atlassian.net/browse/CDS-811)
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
[CDS-811]: https://comfortdelgrotaxi.atlassian.net/browse/CDS-811?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CDS-811] Sub header - add actions example

apps/docs/data/components/avatars/GroupAvatars.tsx, apps/docs/data/components/avatars/GroupAvatars.tsx.preview, apps/docs/data/components/avatars/avatars.md, apps/docs/data/components/icon/icon.md, apps/docs/pages/foundation/overview.tsx
docs-v2 improvement
**1) Changes**
https://comfortdelgrotaxi.atlassian.net/browse/CDS-834
**2) Impact**
=> [CDS-834][docs-v2 improvement]

packages/react-compass/src/theme/keyframes.ts, packages/react-compass/src/toast/service/toast-container.tsx, packages/react-compass/src/toast/service/toast-item.styles.ts
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-719] Toast context provider - Fix bug the "center-center" position

packages/react-compass/src/time-picker/time-picker-dropdown.tsx, packages/react-compass/src/time-picker/time-picker.tsx
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-810] Timepicker - Controlled component without onTimeChange

packages/react-compass/src/button/button.stories.tsx
[CDS-712](https://comfortdelgrotaxi.atlassian.net/browse/CDS-712)
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
[CDS-712]: https://comfortdelgrotaxi.atlassian.net/browse/CDS-712?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CDS-712] Button - add disabled state examples

apps/docs/data/components/image-viewer/ImageViewer.tsx, apps/docs/data/components/image-viewer/ImageViewer.tsx.preview, packages/react-compass/src/image-viewer/ViewerNav.tsx, packages/react-compass/src/image-viewer/ViewerToolbar.tsx, packages/react-compass/src/image-viewer/image-viewer.stories.tsx, packages/react-compass/src/image-viewer/image-viewer.styles.ts, packages/react-compass/src/image-viewer/types.ts
Improve image viewer
https://comfortdelgrotaxi.atlassian.net/browse/CDS-747
https://comfortdelgrotaxi.atlassian.net/browse/CDS-746
https://comfortdelgrotaxi.atlassian.net/browse/CDS-749
**1) Screen shot**
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-747] improve image viewer

apps/docs/data/components/wizard/WizardError.tsx, apps/docs/data/components/wizard/WizardError.tsx.preview, apps/docs/data/components/wizard/wizard.md, packages/react-compass/src/wizard/item/index.tsx, packages/react-compass/src/wizard/wizard.stories.tsx, packages/react-compass/src/wizard/wizard.styles.ts, packages/react-compass/src/wizard/wizard.tsx
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> feature: New error steps for wizard

packages/react-compass/src/avatar/avatar-group.styles.ts, packages/react-compass/src/file/state/index.tsx, packages/react-compass/src/typography/link/index.tsx, packages/react-compass/src/typography/typography.stories.tsx, packages/react-compass/src/video-player/video-player.tsx
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-696, CDS-735, CDS-744, CDS-795] Fix bugs patch 1

apps/docs/components/layouts/DocsAppSideNav.tsx
NavSideApp scroll not cover all items 
**1) Changes**
https://comfortdelgrotaxi.atlassian.net/browse/CDS-851
**2) Impact**
=> [CDS-851] NavSideApp scroll not cover all items

packages/react-compass/src/carousel/readme.md, packages/react-compass/src/gutter/readme.md, packages/react-compass/src/otp-input/readme.md, packages/react-compass/src/popover/README.md, packages/react-compass/src/rating/README.md, packages/react-compass/src/toast/README.md
**2) Changes**
Add readme files to components
**3) Impact**
https://comfortdelgrotaxi.atlassian.net/browse/CDS-822
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-822] add documentation

apps/docs/data/components/dropdown/DropdownControlled.tsx, apps/docs/data/components/dropdown/DropdownControlled.tsx.preview, apps/docs/data/components/dropdown/dropdown.md, packages/react-compass/src/dropdown/dropdown-item.tsx, packages/react-compass/src/dropdown/dropdown.stories.tsx, packages/react-compass/src/dropdown/dropdown.tsx, packages/react-compass/src/dropdown/utils.tsx
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> Add custom display to dropdown

packages/react-compass/src/error/error.styles.ts
Error - Incorrect color/background color in Error component
**1) Changes**
https://comfortdelgrotaxi.atlassian.net/browse/CDS-774
**2) Impact**
=> [CDS-774] Error - Incorrect color/background color in Error component

packages/react-compass/src/quantity-toggle/quantity-toggle.styles.ts, packages/react-compass/src/tag-box/tag-box.styles.ts, packages/react-compass/src/toggle/toggle.styles.ts, packages/react-compass/src/video-player/icon.tsx, packages/react-compass/src/wizard/wizard.tsx
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> fix: CDS-732, CDS-771, CDS-743, CDS-791

packages/react-compass/src/dropdown/dropdown-item.tsx, packages/react-compass/src/dropdown/dropdown.styles.ts
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-705] Update styles of Dropdown

packages/react-compass/src/textfield/textfield.styles.ts
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-772] border with text field

packages/react-compass/src/multiple-dropdown/multiple-dropdown.styles.ts
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-726] Update styles of multiple-dropdown

packages/react-compass/src/chip/chip.stories.tsx, packages/react-compass/src/chip/chip.styles.tsx, packages/react-compass/src/chip/chip.tsx
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-781] [CDS-784]Add accessibility and fix bug large content for Chip

packages/react-compass/src/searchfield/searchfield.stories.tsx, packages/react-compass/src/searchfield/searchfield.styles.ts, packages/react-compass/src/searchfield/searchfield.tsx
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-704] [CDS-700] Add props and update style for SearchField

apps/docs/data/components/card/CardShadowless.tsx, apps/docs/data/components/card/CardShadowless.tsx.preview, apps/docs/data/components/card/card.md, packages/react-compass/src/card/card-title.styles.ts, packages/react-compass/src/card/card.stories.tsx, packages/react-compass/src/card/card.styles.ts
* We didn't cover the case of hovering mouse on shadowless before
* We didn't have any layout of card title with icon button before
**2) Changes**
* Add sample and fix the css
**3) Impact**
https://comfortdelgrotaxi.atlassian.net/browse/CDS-720
https://comfortdelgrotaxi.atlassian.net/browse/CDS-718
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-720][CDS-718] Fix card defects

packages/react-compass/src/auto-complete/autoComplete.styles.tsx, packages/react-compass/src/auto-complete/autoComplete.tsx, packages/react-compass/src/dialog/dialog-trigger.tsx, packages/react-compass/src/dialog/dialog.stories.tsx, packages/react-compass/src/dialog/dialog.styles.ts, packages/react-compass/src/dialog/dialog.tsx, packages/react-compass/src/grid/grid.styles.ts, packages/react-compass/src/modal/modal-trigger.tsx, packages/react-compass/src/modal/modal.stories.tsx, packages/react-compass/src/modal/modal.styles.ts, packages/react-compass/src/modal/modal.tsx, packages/react-compass/src/textarea/textarea.stories.tsx, packages/react-compass/src/textarea/textarea.styles.ts, packages/react-compass/src/textarea/textarea.tsx
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> Fix: fix bugs for autocomplete, textarea, modal, dialog and popover

apps/docs/constants/routes.ts, apps/docs/data/components/app-navigation/AppNav.tsx, apps/docs/data/components/app-navigation/AppNav.tsx.preview, apps/docs/data/components/app-navigation/app-navigation.md, apps/docs/pages/components/app-navigation.tsx, packages/react-compass/src/appnav/appnav-section.tsx, packages/react-compass/src/appnav/appnav.stories.tsx, packages/react-compass/src/appnav/appnav.styles.ts, packages/react-compass/src/appnav/appnav.tsx, packages/react-compass/src/button/button.styles.ts, packages/react-compass/src/button/ripple.tsx
**2) Changes**
- Add ripple effect.
- Add `activeIcon` and `inactiveIcon` props.
- Extend the touchable zone of button.
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [NGPDCP-3058] Enhance appnav and create docs

packages/react-compass/src/accordion/accordion-title.styles.ts
Wrong number of icon size
**2) Changes**
Change to larger icon size
**3) Impact**
https://comfortdelgrotaxi.atlassian.net/browse/CDS-753
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-753] fix accordion icon size

apps/docs/data/components/tooltip/TooltipBackground.tsx, apps/docs/data/components/tooltip/TooltipBackground.tsx.preview, apps/docs/data/components/tooltip/TooltipCustom.tsx, apps/docs/data/components/tooltip/TooltipPlacement.tsx, apps/docs/data/components/tooltip/TooltipPlacement.tsx.preview, apps/docs/data/components/tooltip/tooltip.md, packages/react-compass/src/tooltip/tooltip.stories.tsx, packages/react-compass/src/tooltip/tooltip.styles.ts, packages/react-compass/src/tooltip/tooltip.tsx
Tooltip layout does not follow the Figma design
Some of styles are not so good
**2) Changes**
As discussed with Designer:
* Default background will be black `typeHeading`
* Default font size should be 14px
* Default padding should be: 8px 16px
* User can customize background
Also added more samples:
**3) Impact**
No changes required, but default background will be `typeHeading` (almost black)
https://comfortdelgrotaxi.atlassian.net/browse/CDS-802
https://comfortdelgrotaxi.atlassian.net/browse/CDS-803
```
(1)
```
```
(2)
NO …
```
=> [CDS-802][CDS-803] Fix for tooltip layout

packages/react-compass/src/textfield/textfield.tsx, packages/static/src/chip/chip.tsx, packages/static/src/utils/objectToCss/CssInjection.tsx, packages/static/src/utils/objectToCss/object-to-css.ts, packages/static/vite.config.ts
…ive in static folder
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> Fix/duplicate css in textfield and remove 'use client'

packages/react-compass/src/sidebar/sidebar.stories.tsx, packages/react-compass/src/sidebar/sidebar.styles.ts
Wrong layout implementation
**2) Changes**
Change to flex layout instead of absolute position
**3) Impact**
All sidebar layout
https://comfortdelgrotaxi.atlassian.net/browse/CDS-813
https://comfortdelgrotaxi.atlassian.net/browse/CDS-800
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-800][CDS-813] Fix sidebar layout

packages/react-compass/src/rich-text-editor/controls/DropdownControls/HeadingsControl.tsx, packages/react-compass/src/rich-text-editor/controls/DropdownControls/TextAlignmentSelectorControl.tsx, packages/react-compass/src/rich-text-editor/controls/ImageControl/ImageControl.tsx, packages/react-compass/src/rich-text-editor/controls/LinkControl/LinkControl.tsx, packages/react-compass/src/rich-text-editor/rich-text-editor.context.ts, packages/react-compass/src/rich-text-editor/rich-text-editor.tsx
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-817][CDS-819] Rich text editor - update dropdown selected key and fix link control

packages/react-compass/src/multiple-dropdown/multiple-dropdown.tsx
Missing logic for keys(backward)
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> Fix backward compatible for MultipleDropdown

apps/docs/components/common/CodeCopyButton.tsx, apps/docs/components/common/Demo.tsx, apps/docs/components/common/DemoToolbar.tsx, apps/docs/components/common/MarkdownElement.tsx, apps/docs/components/layouts/AppHeader.tsx, apps/docs/components/layouts/AppNavbarMobile.tsx, apps/docs/components/layouts/AppSearch.tsx, apps/docs/components/layouts/DocsAppFrame.tsx, apps/docs/constants/config.ts, apps/docs/constants/index.ts, apps/docs/pages/_app.tsx, apps/docs/pages/global.css
- https://comfortdelgrotaxi.atlassian.net/browse/CDS-846
- https://comfortdelgrotaxi.atlassian.net/browse/CDS-844
- https://comfortdelgrotaxi.atlassian.net/browse/CDS-847
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-846] Improve docs

packages/react-compass/src/richtext-render/renderDocument.tsx, packages/react-compass/src/richtext-render/richtext-renderer.stories.tsx, packages/react-compass/src/richtext-render/richtextRender.tsx
**2) Changes**
- update function `RenderDocument`
- new props `platform`
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-868] fix bug, add rich text renderer stories

packages/react-compass/src/menu-list/menu-list-dropdown.styles.tsx, packages/react-compass/src/menu-list/menu-list.styles.ts
MenuList does not follow the Figma design
Some of styles are not so good
**2) Changes**
Default background will be `primaryBg`
**3) Impact**
[](https://comfortdelgrotaxi.atlassian.net/browse/CDS-707)
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-706] [CDS-707] MenuList does not follow the Figma design

packages/react-compass/src/table-v2/table-v2-column-header-filter.styles.ts, packages/react-compass/src/table-v2/table-v2-column-header-filter.tsx, packages/react-compass/src/table/table.stories.tsx
**1) Changes**
Table column filter feature.
**2) Impact**
Table component - Column filter feature.
[CDS-837](https://comfortdelgrotaxi.atlassian.net/browse/CDS-837)
[CDS-838](https://comfortdelgrotaxi.atlassian.net/browse/CDS-838)
[CDS-839](https://comfortdelgrotaxi.atlassian.net/browse/CDS-839)
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
[CDS-837]: https://comfortdelgrotaxi.atlassian.net/browse/CDS-837?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjo …
=> [CDS-837, CDS-838, CDS-839] Table column filter feature

apps/docs/constants/routes.ts, apps/docs/data/components/dropdown-textfield/DropdownTextfield.tsx, apps/docs/data/components/dropdown-textfield/DropdownTextfield.tsx.preview, apps/docs/data/components/dropdown-textfield/dropdown-textfield.md, apps/docs/pages/components/dropdown-textfield.tsx, packages/react-compass/src/dropdown-textfield/dropdown-textfield.stories.tsx, packages/react-compass/src/dropdown-textfield/dropdown-textfield.styles.tsx, packages/react-compass/src/dropdown-textfield/dropdown-textfield.tsx, packages/react-compass/src/dropdown-textfield/index.ts, packages/react-compass/src/dropdown/dropdown.stories.tsx, packages/react-compass/src/dropdown/dropdown.styles.ts, packages/react-compass/src/dropdown/dropdown.tsx, packages/react-compass/src/index.ts, packages/react-compass/src/textarea/textarea.stories.tsx, packages/react-compass/src/textarea/textarea.styles.ts, packages/react-compass/src/textfield/textfield.stories.tsx, packages/react-compass/src/textfield/textfield.styles.ts, packages/react-compass/src/textfield/textfield.tsx
**2) Changes**
- Develop new component: DropdownTextfield, including h5 UI variant
- Update h5 variant for Textfield and Dropdown.Select
- Create docs
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [NGPDCP-2922] h5 textfield variants

apps/docs/data/components/badges/BadgeStatus.tsx, apps/docs/data/components/badges/BadgeStatus.tsx.preview, apps/docs/data/components/badges/badges.md, packages/react-compass/src/badge/badge.stories.tsx, packages/react-compass/src/badge/badge.styles.ts, packages/react-compass/src/theme/theme.ts
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-689]  Add status component for badge component

packages/react-compass/src/list/list.styles.ts, packages/react-compass/src/list/list.tsx
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-858] Refactor style for List

apps/docs/data/components/toast/ToastColor.tsx, apps/docs/data/components/toast/toast.md, packages/react-compass/src/toast/toast.stories.tsx, packages/react-compass/src/toast/toast.styles.ts, packages/react-compass/src/toast/toast.tsx
Prevent users confuse when use Toast or Toast as service
**2) Changes**
- Add position prop for Toast
- Update individual usage of Toast as ToastService
- Update document for Toast service
**3) Impact**
Toast props and document of Toast
[](https://comfortdelgrotaxi.atlassian.net/browse/CDS-856)
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-856] Add position prop to Toast and update document for ToastAsService

packages/react-compass/src/alert/alert.styles.ts, packages/react-compass/src/alert/alert.tsx
fix style follow figma and logic render
**1) Changes**
https://comfortdelgrotaxi.atlassian.net/browse/CDS-688
**2) Impact**
=> [CDS-688][fix style follow figma and logic render]

packages/react-compass/src/footer/footer.styles.ts
Footer does not follow the Figma design on Tablet mode
**2) Changes**
Update padding for Footer on Tablet mode
**3) Impact**
Footer on Tablet mode
https://comfortdelgrotaxi.atlassian.net/browse/CDS-738
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-738] Update padding for Footer mode tablet

apps/docs/pages/global.css, packages/static/src/theme-static/ThemeProvider.tsx, packages/static/src/theme-static/theme.module.css
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> feat update data key theme

packages/react-compass/src/calendar/calendar-cell.style.ts, packages/react-compass/src/calendar/calendar.tsx, packages/react-compass/src/date-picker/date-picker.stories.tsx, packages/react-compass/src/date-range-picker/date-range-picker.stories.tsx, packages/react-compass/src/range-calendar/range-calendar.tsx
The today button does not check the validity of today date 
**2) Changes**
Check the validity of today button, if invalid, disabled the button
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> Fix calendar today button not disable when invalid

packages/static/src/utils/objectToCss/CssInjection.tsx
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> fix: change to HTMLElement

apps/docs/pages/_app.tsx
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> Fix build error

apps/docs/pages/_app.tsx
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> Update _app.tsxt to fix build error

packages/react-compass/src/otp-input/OTPInput.tsx, packages/react-compass/src/otp-input/SingleInput.tsx
[CDS-865](https://comfortdelgrotaxi.atlassian.net/browse/CDS-865)
**2) Impact**
The OTP input component
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
[CDS-865]: https://comfortdelgrotaxi.atlassian.net/browse/CDS-865?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CDS-865] OTP input - autofocus related issue

packages/static/.storybook/main.ts, packages/static/.storybook/preview-head.html, packages/static/package.json, packages/static/src/breadcrumbs/Breadcrumbs.stories.tsx, packages/static/src/breadcrumbs/breadcrumb-item.tsx, packages/static/src/breadcrumbs/breadcrumbs.tsx, packages/static/src/breadcrumbs/index.ts, packages/static/src/breadcrumbs/styles/breadscrumbs-item.module.css, packages/static/src/breadcrumbs/styles/breadscrumbs.module.css, packages/static/src/utils/objectToCss/CssInjection.tsx, pnpm-lock.yaml
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-893] Implementation of breadcrumbs for static

apps/docs/data/components/avatars/CustomAvatars.tsx, apps/docs/data/components/avatars/CustomAvatars.tsx.preview, apps/docs/data/components/avatars/IconAvatars.tsx, apps/docs/data/components/avatars/IconAvatars.tsx.preview, apps/docs/data/components/avatars/LetterAvatars.tsx, apps/docs/data/components/avatars/LetterAvatars.tsx.preview, apps/docs/data/components/avatars/SizesAvatars.tsx, apps/docs/data/components/avatars/SizesAvatars.tsx.preview, apps/docs/data/components/avatars/avatars.md, apps/docs/data/components/badges/BadgeColors.tsx, apps/docs/data/components/badges/BadgeColors.tsx.preview, apps/docs/data/components/badges/BadgeCustomIcon.tsx, apps/docs/data/components/badges/BadgeCustomIcon.tsx.preview, apps/docs/data/components/badges/BadgeVariants.tsx, apps/docs/data/components/badges/BadgeVariants.tsx.preview, apps/docs/data/components/badges/badges.md
**2) Changes**# Merge request description template
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
**3) Impact**
```
(1)
```
```
(2) …
```
=> [docs-v2] add more feature

packages/react-compass/src/carousel/carousel-slider.tsx
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> Fix carousel wrong page number

apps/docs/data/components/dropdown-textfield/Controlled.preview, apps/docs/data/components/dropdown-textfield/Controlled.tsx, apps/docs/data/components/dropdown-textfield/dropdown-textfield.md, packages/react-compass/src/appnav/appnav-section.tsx, packages/react-compass/src/appnav/appnav.styles.ts, packages/react-compass/src/dropdown-textfield/dropdown-textfield.stories.tsx, packages/react-compass/src/dropdown-textfield/dropdown-textfield.tsx, packages/react-compass/src/dropdown/dropdown.styles.ts, packages/react-compass/src/textfield/textfield.styles.ts
**2) Changes**
- update padding in AppNav component.
- Change font size in H5 variant TextField.
- Update component DropdownTextfield.
- Temporarily remove Ripple effect from AppNav buttons.
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> Modify h5 components

packages/static/src/index.ts, packages/static/src/multiple-choices-slider/index.ts, packages/static/src/multiple-choices-slider/multiple-choices-slider-item.tsx, packages/static/src/multiple-choices-slider/multiple-choices-slider.stories.tsx, packages/static/src/multiple-choices-slider/multiple-choices-slider.tsx, packages/static/src/multiple-choices-slider/styles/multiple-choices-slider.module.css
**1) Changes**
Use static CSS instead of stitches
**2) Impact**
Multiple choices slider component
[CDS-927](https://comfortdelgrotaxi.atlassian.net/browse/CDS-927)
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
[CDS-927]: https://comfortdelgrotaxi.atlassian.net/browse/CDS-927?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CDS-927] Multiple choices slider - use static CSS

packages/react-compass/src/sidenav/sidenav-item.styles.ts, packages/react-compass/src/sidenav/sidenav.stories.tsx
There's no limit of item width
**2) Changes**
Set max width with a safe number
**3) Impact**
https://comfortdelgrotaxi.atlassian.net/browse/CDS-815
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-815] Fix slidenav text overflow

apps/docs/data/customization/theming/theming.md, packages/static/src/theme/ThemeProvider.tsx
Update docs for static theme
Screenshot
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-884] Update docs for static theme

apps/docs/package.json
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> Fix package.json

packages/static/src/button/button.tsx
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> Fix button prop type

packages/static/src/avatar/avatar.tsx
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> fix: avatar class

packages/static/.storybook/main.ts
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> Fix bugs in storybook

packages/react-compass/src/button/button.styles.ts, packages/static/src/button/button.stories.tsx, packages/static/src/button/button.tsx, packages/static/src/button/styles/button.module.css, packages/static/src/scripts/theme.config.js, packages/static/src/theme/theme.module.css, packages/static/src/theme/theme.ts
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> Fix bugs in static/button

packages/static/src/layouts/index.ts, packages/static/src/layouts/layout/Layout.stories.tsx, packages/static/src/layouts/layout/index.ts, packages/static/src/layouts/layout/layout.const.ts, packages/static/src/layouts/layout/layout.tsx, packages/static/src/layouts/layout/styles/layout.module.css
**2) Changes**
**3) Impact**
https://comfortdelgrotaxi.atlassian.net/browse/CDS-934
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-934] Add new Layout component

packages/static/src/badge/badge.stories.tsx, packages/static/src/badge/badge.tsx, packages/static/src/badge/index.ts, packages/static/src/badge/styles/badge.module.css, packages/static/src/index.ts, packages/static/src/scripts/theme.config.js, packages/static/src/theme/theme.module.css, packages/static/src/theme/theme.ts, packages/static/src/utils/get-icon-from-color.tsx, pnpm-lock.yaml
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS - 907] Add static css version of Badge

packages/static/src/auto-complete/autoComplete.stories.tsx, packages/static/src/auto-complete/autoComplete.tsx, packages/static/src/auto-complete/index.ts, packages/static/src/auto-complete/styles/autoComplete.module.css, packages/static/src/index.ts, pnpm-lock.yaml
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS - 817] add static css version of AutoComplete

packages/static/src/textfield/styles/textfield.module.css, packages/static/src/textfield/textfield.tsx, packages/static/src/time-picker/styles/time-picker.module.css
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> Write css without nested classes

packages/react-compass/src/confirm-pickup/confirm-pickup.tsx, packages/static/src/confirm-pickup/confirm-pickup.stories.tsx, packages/static/src/confirm-pickup/confirm-pickup.tsx, packages/static/src/confirm-pickup/index.ts, packages/static/src/confirm-pickup/styles/confirm-pickup.module.css, packages/static/src/index.ts
**1) Changes**
Use static CSS
**2) Impact**
The Confirm Pickup component
[CDS-928](https://comfortdelgrotaxi.atlassian.net/browse/CDS-928)
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
[CDS-928]: https://comfortdelgrotaxi.atlassian.net/browse/CDS-928?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CDS-928] Confirm Pickup - Static CSS

packages/react-compass/src/otp-input/SingleInput.tsx, packages/static/src/index.ts, packages/static/src/otp-input/OTPInput.tsx, packages/static/src/otp-input/SingleInput.tsx, packages/static/src/otp-input/index.ts, packages/static/src/otp-input/otpInput.stories.tsx, packages/static/src/otp-input/otpInput.styles.ts, packages/static/src/otp-input/readme.md, packages/static/src/otp-input/styles/otpInput.module.css, packages/static/src/otp-input/usePrevious.ts
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS - 947] Add static css version of OTP input

packages/static/src/index.ts, packages/static/src/toast/README.md, packages/static/src/toast/hooks/useToast.ts, packages/static/src/toast/index.ts, packages/static/src/toast/service/index.ts, packages/static/src/toast/service/toast-container.tsx, packages/static/src/toast/service/toast-context.tsx, packages/static/src/toast/service/toast-item.tsx, packages/static/src/toast/service/toast-reducer.ts, packages/static/src/toast/service/types.ts, packages/static/src/toast/styles/toast.module.css, packages/static/src/toast/toast-actions.tsx, packages/static/src/toast/toast-closeIcon.tsx, packages/static/src/toast/toast-icon.tsx, packages/static/src/toast/toast-label.tsx, packages/static/src/toast/toast-message.tsx, packages/static/src/toast/toast-service.ts, packages/static/src/toast/toast-title.tsx, packages/static/src/toast/toast.stories.tsx, packages/static/src/toast/toast.tsx
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-882] convert Toast component to static css

pnpm-lock.yaml
fix lock file
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [hot fix] fix lockfile

apps/docs/data/components/banner/banner.md
fix docs
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [hot fix] fix docs

packages/react-compass/src/otp-input/OTPInput.tsx, packages/static/src/otp-input/OTPInput.tsx
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-976] OTP input not trigger onchange when paste from clipboard

.github/workflows/deploy-site.yml, .github/workflows/release-sit.yml, .github/workflows/release.yml
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> Update git action

.github/workflows/deploy-site.yml, .github/workflows/release-sit.yml, .github/workflows/release.yml
Reverts comfortdelgro/compass-design#1348
=> Revert "Update git action"

pnpm-lock.yaml
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [hotfix] update lock file

pnpm-lock.yaml
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [hotfix] re-use lock file

packages/static/src/divider/Divider.stories.tsx, packages/static/src/divider/divider.tsx, packages/static/src/divider/styles/divider.module.css
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-970] Apply css layer for divider

packages/static/src/checkbox/Checkbox.stories.tsx, packages/static/src/checkbox/checkbox.tsx, packages/static/src/checkbox/styles/checkbox.module.css
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-971] Apply css layer for checkbox

packages/static/src/index.ts, packages/static/src/page-header/PageHeader.stories.tsx, packages/static/src/page-header/index.ts, packages/static/src/page-header/page-header-description.tsx, packages/static/src/page-header/page-header-header.tsx, packages/static/src/page-header/page-header-subtitle.tsx, packages/static/src/page-header/page-header-title.tsx, packages/static/src/page-header/page-header.tsx, packages/static/src/page-header/styles/page-header-description.module.css
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-969] Feature: page header static

packages/static/src/breadcrumbs/Breadcrumbs.stories.tsx, packages/static/src/breadcrumbs/breadcrumb-item.tsx, packages/static/src/breadcrumbs/breadcrumbs.tsx, packages/static/src/breadcrumbs/styles/breadscrumbs-item.module.css, packages/static/src/breadcrumbs/styles/breadscrumbs.module.css
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-974] Apply css layer for breadcrumbs

packages/static/instruction.md, packages/static/src/progress/Progress.stories.tsx, packages/static/src/progress/progress.circular.tsx, packages/static/src/progress/progress.linear.tsx, packages/static/src/progress/styles/circular.module.css, packages/static/src/progress/styles/linear.module.css
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-978] Apply css layer for progress

packages/react-compass/src/tabs/tabs.styles.ts, packages/static/src/tabs/styles/tabs.module.css, pnpm-lock.yaml
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-982] Tabs breaks on Safari

packages/react-compass/src/textfield/textfield.styles.ts, packages/static/src/textfield/styles/textfield.module.css
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> Fix the hidden left icon

packages/static/src/checkbox/styles/checkbox.module.css
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-983] Checkbox mismatch selected style

packages/static/src/dropdown-textfield/dropdown-textfield.stories.tsx, packages/static/src/dropdown-textfield/dropdown-textfield.tsx, packages/static/src/dropdown-textfield/index.ts, packages/static/src/dropdown-textfield/styles/dropdown-textfield.module.css, packages/static/src/dropdown/dropdown.tsx, packages/static/src/dropdown/styles/dropdown.module.css, packages/static/src/index.ts
**2) Changes**
[](https://comfortdelgrotaxi.atlassian.net/browse/CDS-989)
**3) Impact**
[](https://comfortdelgrotaxi.atlassian.net/browse/CDS-989)
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-989] Convert Dropdown-Textfield to static css

packages/static/src/utils/components.module.css
add utils component styles
**2) Changes**
[](https://comfortdelgrotaxi.atlassian.net/browse/CDS-988)
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-988] add utils component styles

packages/static/src/index.ts, packages/static/src/snackbar/hooks/useSnackbar.ts, packages/static/src/snackbar/index.tsx, packages/static/src/snackbar/service/index.ts, packages/static/src/snackbar/service/snackbar-container.tsx, packages/static/src/snackbar/service/snackbar-context.tsx, packages/static/src/snackbar/service/snackbar-item.tsx, packages/static/src/snackbar/service/snackbar-reducer.ts, packages/static/src/snackbar/service/snackbar-service.ts, packages/static/src/snackbar/service/types.ts, packages/static/src/snackbar/snackbar-prefix-icon.tsx, packages/static/src/snackbar/snackbar-suffix-icon.tsx, packages/static/src/snackbar/snackbar-text.tsx, packages/static/src/snackbar/snackbar.stories.tsx, packages/static/src/snackbar/snackbar.tsx, packages/static/src/snackbar/styles/snackbar-item.module.css, packages/static/src/snackbar/styles/snackbar.module.css
change static for snack bar component
**2) Changes**
[](https://comfortdelgrotaxi.atlassian.net/browse/CDS-987)
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-987] change static for snack bar component

apps/docs/data/components/error/ErrorServer.tsx, apps/docs/data/components/error/error.md, packages/static/src/error/error-action.tsx, packages/static/src/error/error-description.tsx, packages/static/src/error/error-icon.tsx, packages/static/src/error/error-image.tsx, packages/static/src/error/error-title.tsx, packages/static/src/error/error.stories.tsx, packages/static/src/error/error.tsx, packages/static/src/error/index.ts, packages/static/src/error/styles/error.module.css, packages/static/src/index.ts
change static for error component
**2) Changes**
[](https://comfortdelgrotaxi.atlassian.net/browse/CDS-986)
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-986] change static for error component

packages/static/.storybook/addons/theme/Tool.tsx, packages/static/.storybook/main.ts
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> feat: enable theme for storybook

packages/static/src/index.ts, packages/static/src/upload/common.ts, packages/static/src/upload/index.ts, packages/static/src/upload/styles/upload.module.css, packages/static/src/upload/upload-drag-and-drop/index.tsx, packages/static/src/upload/upload-drag-and-drop/upload-drag-and-drop.module.css, packages/static/src/upload/upload.stories.tsx, packages/static/src/upload/upload.tsx
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-967] upload static css new

package.json
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> add publish directory

packages/react-compass/src/tooltip/tooltip-trigger.tsx, packages/static/src/tooltip/tooltip-trigger.tsx
Tooltip renders portal even when not hover
**2) Changes**
Only render portal when hover a tooltip
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> Enhancement: Tooltip portal render

apps/docs/data/components/dialog/DialogMobile.tsx, apps/docs/data/components/dialog/DialogMobile.tsx.preview, apps/docs/data/components/dialog/dialog.md
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> Add examples of using dialog in mobile devices

apps/docs/data/components/toggle/ToggleIsDisabled.tsx, apps/docs/data/components/toggle/ToggleSizes.tsx, apps/docs/data/components/toggle/toggle.md, packages/react-compass/src/preflight/preflight.styles.ts, packages/static/src/preflight/styles/preflight.module.css, packages/static/src/rich-text-editor/styles/rich-text-editor.module.css
Verify static components
**2) Changes**
* Add more sample for toggle.
* Fix richtext icon margin issue
* Fix richtext overflow image
**3) Impact**
https://comfortdelgrotaxi.atlassian.net/browse/CDS-993
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-993] Fix for static components batch 2

apps/docs/data/components/drawer/Drawer.tsx, apps/docs/data/components/drawer/DrawerCustomize.tsx, apps/docs/data/components/drawer/DrawerH5.tsx, apps/docs/data/components/drawer/DrawerMode.tsx, apps/docs/data/components/drawer/DrawerPosition.tsx, apps/docs/data/components/drawer/drawer.md, apps/docs/data/components/multiple-choices-slider/MultipleChoicesSlider.tsx, apps/docs/data/components/multiple-choices-slider/multiple-choices-slider.md, apps/docs/data/components/pudo/Pudo.tsx, apps/docs/data/components/pudo/PudoAlignIcon.tsx, apps/docs/data/components/pudo/PudoCompact.tsx, apps/docs/data/components/pudo/PudoCustomType.tsx, apps/docs/data/components/pudo/PudoH5Example.tsx, apps/docs/data/components/pudo/PudoManipulation.tsx, apps/docs/data/components/pudo/pudo.md, apps/docs/data/components/slide-action/SlideAction.tsx, apps/docs/data/components/slide-action/SlideActionBehavior.tsx, apps/docs/data/components/slide-action/SlideActionIcon.tsx, apps/docs/data/components/slide-action/SlideColorful.tsx, apps/docs/data/components/slide-action/SlideCompact.tsx, apps/docs/data/components/slide-action/SlideEffect.tsx, apps/docs/data/components/slide-action/slide-action.md, apps/docs/data/components/slider/SliderBasic.tsx, apps/docs/data/components/slider/slider.md
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-992] import these following components for their documentation pages from new react-compass

packages/react-compass/src/pagination/pagination.hooks.ts, packages/react-compass/src/pagination/pagination.tsx, packages/static/src/pagination/pagination.hooks.ts, packages/static/src/pagination/pagination.tsx
Fix Pagination stale closure
**2) Changes**
Hotfix high priority
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [Hotfix] Pagination stale closure

packages/react-compass/src/image-viewer/ViewerCanvas.tsx, packages/static/src/image-viewer/ViewerCanvas.tsx
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> fix: image viewer center when release mouse

packages/static/src/carousel/index.ts, packages/static/src/index.ts
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> Add exported types from carousel

.changeset/config.json, .changeset/lucky-suits-wonder.md, .changeset/pre.json, packages/react-compass/package.json, packages/static/package.json
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> New release for react-compass

packages/react-compass/src/textarea/textarea.tsx, packages/react-compass/src/textfield/textfield.tsx, packages/static/src/textarea/textarea.tsx, packages/static/src/textfield/textfield.tsx
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-918] TextField - some attributes of HTML input elements are not being used in the right place

packages/react-compass/src/textarea/textarea.tsx, packages/react-compass/src/textfield/textfield.tsx, packages/static/src/textarea/textarea.tsx, packages/static/src/textfield/textfield.tsx
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> fix: move htmlprops to wrapper

packages/react-compass/src/pudo/pudo-item.tsx, packages/react-compass/src/pudo/pudo.stories.tsx, packages/react-compass/src/pudo/pudo.styles.ts, packages/react-compass/src/pudo/pudo.tsx, packages/react-compass/src/pudo/pudo.types.ts, packages/static/src/pudo/pudo-item.tsx, packages/static/src/pudo/pudo.stories.tsx, packages/static/src/pudo/pudo.tsx, packages/static/src/pudo/pudo.types.ts, packages/static/src/pudo/styles/pudo.module.css
**1) Changes**
Styling
**2) Impact**
The PUDO component
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> PUDO: CSS styles - complexity reduction

apps/docs/data/components/footer/FooterColorVariants.tsx, packages/static/src/footer/Footer.stories.tsx, packages/static/src/footer/footer-nav.tsx, packages/static/src/footer/styles/footer-header.module.css, packages/static/src/footer/styles/footer-info-social.module.css, packages/static/src/footer/styles/footer-info.module.css, packages/static/src/footer/styles/footer-nav.module.css, packages/static/src/footer/styles/footer-policy.module.css, packages/static/src/footer/styles/footer.module.css
* Grid layout is not really good for many cases
* It's complicated to let user send in number of columns
* Does not switch to mobile mode when wrapper is small because of media query
**2) Changes**
* Change gridNumber to optional, to not requires user to config it up
* Let the columns grow on screen automatically or based on user config using their css
* Add container queries to transform layout more effectively when we have other elements on the side
**3) Impact**
Footer layout, no update requires from the other teams.
https://comfortdelgrotaxi.atlassian.net/browse/CDS-739
```
(1)
Boilerplate codes is duplicated multiple times a bunch of the same code. This should be a common function to reuse through your code or you can use generic class / methods or design pattern to …
```
=> [CDS-739] Fix for footer responsive layout

packages/static/src/rich-text-editor/controls/ControlsGroup/index.tsx, packages/static/src/rich-text-editor/controls/DropdownControls/ColorControl.tsx, packages/static/src/rich-text-editor/controls/DropdownControls/HeadingsControl.tsx, packages/static/src/rich-text-editor/controls/DropdownControls/TextAlignmentSelectorControl.tsx, packages/static/src/rich-text-editor/styles/control.module.css, packages/static/src/rich-text-editor/styles/dropdown.module.css, packages/static/src/rich-text-editor/styles/toolbar.module.css, packages/static/src/rich-text-editor/toolbar/index.tsx
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [react][Defect] RichTextEditor - Toolbar is wrong after click multiple times on Firefox

packages/static/src/badge/styles/badge.module.css, packages/static/src/box/box.tsx
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-1016] Fixing build error for static

apps/docs/data/components/toggle/ToggleControlled.tsx.preview, apps/docs/data/components/toggle/ToggleCustomStyling.tsx.preview, apps/docs/data/components/toggle/ToggleIsDisabled.tsx.preview, apps/docs/data/components/toggle/ToggleIsReadOnly.tsx.preview, apps/docs/data/components/toggle/ToggleServer.tsx.preview, apps/docs/data/components/toggle/ToggleSizes.tsx.preview, apps/docs/data/components/toggle/ToggleUnControlled.tsx.preview
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-1015] Missing preview file in toggle docs

apps/docs/data/components/otp-input/OTPInput.tsx, apps/docs/data/components/otp-input/OTPInput.tsx.preview, apps/docs/data/components/otp-input/otp-input.md, packages/static/src/otp-input/OTPInput.tsx, packages/static/src/otp-input/SingleInput.tsx, packages/static/src/otp-input/otpInput.stories.tsx, packages/static/src/otp-input/styles/otpInput.module.css
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> feat: CDS-949

apps/docs/constants/routes.ts, apps/docs/data/components/speed-dial2/SpeedDial.tsx, apps/docs/data/components/speed-dial2/SpeedDial.tsx.preview, apps/docs/data/components/speed-dial2/SpeedDialHover.tsx, apps/docs/data/components/speed-dial2/SpeedDialHover.tsx.preview, apps/docs/data/components/speed-dial2/SpeedDialLeft.tsx, apps/docs/data/components/speed-dial2/SpeedDialLeft.tsx.preview, apps/docs/data/components/speed-dial2/SpeedDialRight.tsx, apps/docs/data/components/speed-dial2/SpeedDialRight.tsx.preview, apps/docs/data/components/speed-dial2/SpeedDialServer.tsx, apps/docs/data/components/speed-dial2/speed-dial.md, apps/docs/pages/components/speed-dial2.tsx, packages/react-compass/src/preflight/preflight.styles.ts, packages/static/src/index.ts, packages/static/src/preflight/styles/preflight.module.css, packages/static/src/speed-dial-2/index.ts, packages/static/src/speed-dial-2/speed-dial-actions.tsx, packages/static/src/speed-dial-2/speed-dial-button.tsx, packages/static/src/speed-dial-2/speed-dial.stories.tsx, packages/static/src/speed-dial-2/speed-dial.tsx, packages/static/src/speed-dial-2/styles/speed-dial.module.css, packages/static/src/speed-dial/speed-dial.tsx
* Current speed dial component is not good
**2) Changes**
* Add new version 2 of speed dial
* Support user to customize everything
* Add demo
**3) Impact**
https://comfortdelgrotaxi.atlassian.net/browse/CDS-1005
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-1005] Feature/refactor speed dial

apps/docs/data/components/time-picker/TimePickerBasic.tsx.preview, apps/docs/data/components/time-picker/TimePickerControlled12Hours.tsx.preview, apps/docs/data/components/time-picker/TimePickerControlled24Hours.tsx.preview, apps/docs/data/components/time-picker/TimePickerIsDisabled.tsx.preview, apps/docs/data/components/time-picker/TimePickerIsReadOnly.tsx.preview, apps/docs/data/components/time-picker/TimePickerUncontrolled12Hours.tsx.preview, apps/docs/data/components/time-picker/TimePickerUncontrolled24Hours.tsx.preview
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-1019] Missing preview file in time-picker docs

apps/docs/data/components/toast/ToastAsAService.tsx, apps/docs/data/components/toast/ToastAsAService.tsx.preview, apps/docs/data/components/toast/ToastAutoClose.tsx, apps/docs/data/components/toast/ToastAutoClose.tsx.preview, apps/docs/data/components/toast/ToastColor.tsx, apps/docs/data/components/toast/ToastColor.tsx.preview, apps/docs/data/components/toast/ToastDefault.tsx, apps/docs/data/components/toast/ToastDefault.tsx.preview
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-1020] Missing preview file in toast docs

apps/docs/data/components/transitions/TransitionsCollapse.tsx, apps/docs/data/components/transitions/TransitionsCollapse.tsx.preview, apps/docs/data/components/transitions/TransitionsFade.tsx, apps/docs/data/components/transitions/TransitionsFade.tsx.preview, apps/docs/data/components/transitions/TransitionsSlide.tsx, apps/docs/data/components/transitions/TransitionsSlide.tsx.preview, apps/docs/data/components/transitions/TransitionsZoom.tsx, apps/docs/data/components/transitions/TransitionsZoom.tsx.preview
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-1021] Missing preview file in transition docs

apps/docs/data/components/spinner/SpinnerBasic.tsx, apps/docs/data/components/spinner/SpinnerBasic.tsx.preview, apps/docs/data/components/spinner/SpinnerCustomLabel.tsx, apps/docs/data/components/spinner/SpinnerCustomLabel.tsx.preview, apps/docs/data/components/spinner/SpinnerCustomStyling.tsx, apps/docs/data/components/spinner/SpinnerCustomStyling.tsx.preview, apps/docs/data/components/spinner/SpinnerWithoutLabel.tsx, apps/docs/data/components/spinner/SpinnerWithoutLabel.tsx.preview
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-1022] Missing preview file in spinner docs

packages/static/src/spinner/styles/spinner.module.css
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-1023] Size of spinners is not correct

apps/docs/data/components/button/LinkButton.tsx, apps/docs/data/components/button/LinkButton.tsx.preview, apps/docs/data/components/button/button.md
update docs for button
**2) Changes**
https://comfortdelgrotaxi.atlassian.net/browse/CDS-1029
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-1029] Update docs (adding more props) for the new docs

packages/static/src/navbar/navbar-actions.tsx, packages/static/src/navbar/navbar-brand.tsx, packages/static/src/navbar/navbar.tsx
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-1041] Remove clsx from navbar

packages/static/src/multiple-choices-slider/multiple-choices-slider-item.tsx, packages/static/src/multiple-choices-slider/multiple-choices-slider.tsx
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-1040] Remove clsx from multiple choises slider

apps/docs/data/components/drawer/drawer.md, apps/docs/data/components/pudo/pudo.md, packages/react-compass/src/pudo/pudo.tsx, packages/react-compass/src/pudo/pudo.types.ts, packages/static/src/pudo/pudo.tsx, packages/static/src/pudo/pudo.types.ts
CR for adding new feature.
**2) Changes**
Introduce the `onItemSwap` listener.
**3) Impact**
PUDO component
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> PUDO - add item swap event listener

apps/docs/data/components/time-picker/TimePickerMinTime.preview, apps/docs/data/components/time-picker/TimePickerMinTime.tsx, apps/docs/data/components/time-picker/time-picker.md, packages/react-compass/src/time-picker/time-picker-dropdown-item.tsx, packages/react-compass/src/time-picker/time-picker-dropdown.tsx, packages/react-compass/src/time-picker/time-picker.stories.tsx, packages/react-compass/src/time-picker/time-picker.tsx, packages/static/src/time-picker/time-picker-dropdown-item.tsx, packages/static/src/time-picker/time-picker-dropdown.tsx, packages/static/src/time-picker/time-picker.stories.tsx, packages/static/src/time-picker/time-picker.tsx
**2) Changes**
[](https://comfortdelgrotaxi.atlassian.net/browse/CDS-1035)
**3) Impact**
[](https://comfortdelgrotaxi.atlassian.net/browse/CDS-1035)
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-1035] Add minTIme to timepicker

packages/static/src/menu-list/menu-list-dropdown-header.tsx, packages/static/src/menu-list/menu-list-dropdown-item.tsx, packages/static/src/menu-list/menu-list-dropdown.tsx, packages/static/src/menu-list/menu-list.tsx
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-1039] Remove clsx from menu list

packages/static/src/footer/footer-header.tsx, packages/static/src/footer/footer-info-download.tsx, packages/static/src/footer/footer-info-social.tsx, packages/static/src/footer/footer-info.tsx, packages/static/src/footer/footer-nav.tsx, packages/static/src/footer/footer-policy.tsx, packages/static/src/footer/footer.tsx
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-1038] Remove clsx from footer

packages/static/src/drawer/drawer-expander.tsx, packages/static/src/drawer/drawer-footer.tsx, packages/static/src/drawer/drawer-header.tsx, packages/static/src/drawer/drawer.tsx
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-1037] Remove clsx from drawer

packages/static/src/confirm-pickup/confirm-pickup.tsx, packages/static/src/confirm-pickup/styles/confirm-pickup.module.css
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-1036] Remove clsx from confirm pickup

packages/static/src/box/box.tsx
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-1034] Remove clsx from box

packages/static/src/appnav/appnav-section.tsx, packages/static/src/appnav/appnav.tsx
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-1033] Remove clsx from appnav

apps/docs/pages/foundation/overview.tsx
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-1030] Docs - Losing style when redirect to foundation overview

apps/docs/pages/global.css
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-1027] Home page's Ready to use is overflow

apps/docs/components/home/Introduction/item.tsx, apps/docs/data/components/divider/DividerAlign.tsx, apps/docs/data/components/divider/DividerBasic.tsx
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-1028] Using of color variable is wrong on docs

packages/react-compass/src/pagination/pagination.tsx, packages/static/src/pagination/pagination.tsx
Fixed row per page
**2) Changes**
https://comfortdelgrotaxi.atlassian.net/browse/CDS-1026
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-1026]Pagination rows per pages not change

packages/static/src/button/button.tsx, packages/static/src/button/styles/button.module.css
display: inline cause this error
**2) Changes**
https://comfortdelgrotaxi.atlassian.net/browse/CDS-1007
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-1007]Link button appearance deforms when using with list tag

.changeset/fair-suns-vanish.md, packages/react-compass/package.json, packages/static/package.json
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> New major release

packages/static/src/page-header/page-header-description.tsx, packages/static/src/page-header/page-header-header.tsx, packages/static/src/page-header/page-header-subtitle.tsx, packages/static/src/page-header/page-header-title.tsx, packages/static/src/page-header/page-header.tsx
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-1043] Remove clsx from page header

packages/static/src/pagination/pagination.tsx
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-1044] Remove clsx from pagination

packages/static/src/pudo/pudo-item.tsx, packages/static/src/pudo/pudo.tsx
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-1045] Remove clsx from pudo

packages/static/src/slide-action/slide-action.stories.tsx, packages/static/src/slide-action/slide-action.tsx, packages/static/src/slide-action/slide-dragger.tsx
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-1047] Remove clsx from slide action

packages/static/src/slider/slider.tsx, packages/static/src/slider/styles/slider.module.css
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-1048] Remove clsx from slider

packages/static/src/utils/mergeProps/index.ts
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-1049] Remove clsx from merge props ultils

packages/static/src/dropdown/dropdown-item.tsx, packages/static/src/dropdown/dropdown-list.tsx, packages/static/src/dropdown/dropdown.section.tsx, packages/static/src/dropdown/dropdown.tsx, packages/static/src/dropdown/styles/dropdown.module.css
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-1054] Dropdown item losing style when passing a classname

packages/static/package.json, pnpm-lock.yaml
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-1050] Remove clsx out of repository

packages/static/src/speed-dial/speed-dial-action.tsx, packages/static/src/speed-dial/speed-dial-trigger.tsx, packages/static/src/speed-dial/speed-dial.tsx
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-1051] Refactor speed dial 1 styling

packages/static/src/tag-box-v2/styles/tag-box-v2.module.css, packages/static/src/tag-box-v2/tag-box-v2.tsx
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-1057 ] Refactor tag box 2 styling

apps/docs/data/components/toast/toast.md, packages/react-compass/src/theme/keyframes.ts, packages/react-compass/src/toast/service/toast-container.tsx, packages/react-compass/src/toast/service/toast-context.tsx, packages/react-compass/src/toast/service/toast-item.styles.ts, packages/react-compass/src/toast/service/toast-item.tsx, packages/react-compass/src/toast/service/types.ts, packages/react-compass/src/toast/stories.css, packages/react-compass/src/toast/toast.stories.tsx, packages/static/src/toast/service/toast-container.tsx, packages/static/src/toast/service/toast-context.tsx, packages/static/src/toast/service/toast-item.tsx, packages/static/src/toast/service/types.ts, packages/static/src/toast/stories.css, packages/static/src/toast/styles/toast.module.css, packages/static/src/toast/toast.stories.tsx
**2) Changes**
[](https://comfortdelgrotaxi.atlassian.net/browse/CDS-1056)
**3) Impact**
[](https://comfortdelgrotaxi.atlassian.net/browse/CDS-1056)
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-1056] Fix animation & className for ToastItem

apps/docs/data/components/toast/ToastWithHeader.tsx, apps/docs/data/components/toast/ToastWithHeader.tsx.preview, apps/docs/data/components/toast/toast.md, packages/static/src/toast/styles/toast.module.css, packages/static/src/toast/toast.stories.tsx, packages/static/src/toast/toast.tsx
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-1081] Adding new props withHeader for Toast components

packages/react-compass/src/dropdown/dropdown-context.ts, packages/react-compass/src/dropdown/dropdown-item.tsx, packages/react-compass/src/dropdown/dropdown.tsx, packages/react-compass/src/dropdown/utils.tsx, packages/react-compass/src/time-picker/time-picker.styles.ts, packages/react-compass/src/time-picker/time-picker.tsx, packages/static/src/dropdown/dropdown-context.ts, packages/static/src/dropdown/dropdown-item.tsx, packages/static/src/dropdown/dropdown.tsx, packages/static/src/dropdown/utils.tsx, packages/static/src/multiple-dropdown/multiple-dropdown.tsx, packages/static/src/time-picker/styles/time-picker.module.css
**2) Changes**
**3) Impact**
[](https://comfortdelgrotaxi.atlassian.net/browse/CDS-1059)
[](https://comfortdelgrotaxi.atlassian.net/browse/CDS-1078)
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-1059] [CDS-1078] Fix bug Timepicker hour, minute, second item is difficult to scroll

packages/static/src/divider/styles/divider.module.css
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-1080] Divider dark mode incorrect text color

packages/static/src/rich-text-editor/styles/dropdown.module.css, packages/static/src/rich-text-editor/styles/popover.module.css
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-1079] Rich text editor dark mode incorrect background and dropdown

packages/static/src/textarea/styles/textarea.module.css
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-1074 TextArea dark mode incorrect color background

packages/static/src/textfield/styles/textfield.module.css
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-1075 ] Textfield dark mode incorrect color background

packages/static/src/searchfield/styles/searchfield.module.css
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-1073] Searchfield dark mode incorrect color background

apps/docs/data/components/dashboard-sidecard/DashboardSidecard.tsx, apps/docs/data/components/dashboard-sidecard/DashboardSidecard.tsx.preview, packages/static/src/dashboard-sidecard/dashboardSidecard.stories.tsx, packages/static/src/dashboard-sidecard/styles/dashboardSidecard.module.css
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-1072] Dashboard Sidecard dark mode incorrect color background

packages/static/src/table-v2/table-v2.tsx, packages/static/src/table/table.stories.tsx, packages/static/src/table/table.tsx
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> feat: add resetSelectionWhenDataChanged to table

packages/static/src/popover/popover.tsx, packages/static/src/time-picker/time-picker.tsx
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> Fix bug cannot open dropdown TImePicker

packages/static/src/pudo/styles/pudo.module.css
**1) Changes**
PUDO component
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> PUDO: Minor UI improvement

packages/static/src/avatar/avatar.tsx, packages/static/src/avatar/styles/avatar.module.css, packages/static/src/badge/badge.stories.tsx, packages/static/src/button/button.tsx, packages/static/src/preflight/styles/preflight.module.css
Our css are causing some issue on the other sides when they upgrade the package to v4.
**2) Changes**
* Wrap preflight into @layer
* Fix for avatar default size and avoid to scale in flex layout
* Update some stories layout
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> Update css for more compatibility

packages/static/src/appnav/Appnav.stories.tsx, packages/static/src/appnav/appnav-section.tsx, packages/static/src/appnav/appnav.tsx, packages/static/src/appnav/styles/appnav.module.css
* Does not support class name from outside
* Display with bad UX because of small button
* Wrong position, let the other complicated to custom
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> Update style and options for appnav

packages/static/src/index.ts, packages/static/src/natural-drawer/index.ts, packages/static/src/natural-drawer/natural-drawer.tsx, packages/static/src/natural-drawer/types.ts, packages/static/src/utils/index.ts
Build error
**2) Changes**
export interfaces
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> Update exported interfaces

package.json
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> Delete format on build

.changeset/config.json, .github/PULL_REQUEST_TEMPLATE/bugfix_template.md, .github/PULL_REQUEST_TEMPLATE/feature_template.md, .github/pull_request_template.md, .github/workflows/deploy-site.yml, .github/workflows/release-sit.yml, .github/workflows/release.yml, packages/react-compass/package.json
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> Update changeset and github action config

packages/react-compass/src/checkbox/checkbox.tsx, packages/react-compass/src/checkbox/styles/checkbox.module.css, packages/react-compass/src/scripts/theme.config.js, packages/react-compass/src/theme/theme.module.css, packages/react-compass/src/theme/theme.ts
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-1090] Implement dark mode for checkbox

.github/workflows/deploy-site.yml
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> Update deploy script

apps/docs/constants/routes.ts, apps/docs/data/getting-started/upgrading/upgrading.md, apps/docs/pages/getting-started/upgrading.tsx
Not yet have a guidelines to help 3rd to solve problems.
**2) Changes**
Added new page to guide how to solve common problems of upgrading package version from v3 to v4.
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> Add guidelines to guide other to update react-compass version

apps/docs/data/components/drawer/Drawer.tsx, apps/docs/data/components/drawer/DrawerExpose.tsx, packages/react-compass/src/drawer/drawer.stories.tsx, packages/react-compass/src/drawer/styles/drawer.module.css
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-1093] Fix darkmode background and color for Drawer Component

packages/react-compass/src/accordion/accordion-button.tsx, packages/react-compass/src/accordion/accordion-expandIcon.tsx, packages/react-compass/src/accordion/accordion-table.tsx, packages/react-compass/src/accordion/accordion-title.tsx, packages/react-compass/src/accordion/accordion.tsx, packages/react-compass/src/accordion/styles/accordion-button.module.css, packages/react-compass/src/accordion/styles/accordion-title.module.css
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDS-1096] Accordion background is overlap when toggle open

apps/docs/data/getting-started/installation/installation.md
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDGPMG-2913] Duplicated section on compass-design docs

apps/docs/components/layouts/AppSearch.tsx, apps/docs/types/common.ts, apps/docs/utils/search.ts
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDGPMG-2914] Refactor search box on react-compass docs

packages/react-compass/src/table/table.tsx, packages/react-compass/src/table/types.ts
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDGPMG-2908] Table infinite loop when passing onChangeRowSelection

apps/docs/constants/routes.ts, apps/docs/data/components/announcement/Align.tsx, apps/docs/data/components/announcement/Align.tsx.preview, apps/docs/data/components/announcement/Variant.tsx, apps/docs/data/components/announcement/Variant.tsx.preview, apps/docs/data/components/announcement/announcement.md, apps/docs/pages/components/announcement.tsx, packages/react-compass/src/announcement/announcement.stories.tsx, packages/react-compass/src/announcement/banner/body.tsx, packages/react-compass/src/announcement/banner/index.tsx, packages/react-compass/src/announcement/banner/left.tsx, packages/react-compass/src/announcement/banner/right.tsx, packages/react-compass/src/announcement/card/body.tsx, packages/react-compass/src/announcement/card/footer.tsx, packages/react-compass/src/announcement/card/header.tsx, packages/react-compass/src/announcement/card/index.tsx, packages/react-compass/src/announcement/index.ts, packages/react-compass/src/announcement/styles/announcement.module.css, packages/react-compass/src/announcement/styles/banner.module.css, packages/react-compass/src/announcement/styles/card.module.css, packages/react-compass/src/index.ts
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> [CDGPMG-2906] Implement Announcement component for compass-design

.github/workflows/deploy-site.yml, .github/workflows/release-sit.yml, .github/workflows/release.yml, packages/react-compass/CHANGELOG.md, packages/react-compass/package.json
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> merge main to develop

packages/react-compass/src/accordion/accordion-button.tsx, packages/react-compass/src/accordion/accordion-expandIcon.tsx, packages/react-compass/src/accordion/accordion-table.tsx, packages/react-compass/src/accordion/accordion-title.tsx, packages/react-compass/src/accordion/accordion.tsx, packages/react-compass/src/accordion/index.ts, packages/react-compass/src/alert/alert.tsx, packages/react-compass/src/announcement/banner/body.tsx, packages/react-compass/src/announcement/banner/index.tsx, packages/react-compass/src/announcement/banner/left.tsx, packages/react-compass/src/announcement/banner/right.tsx, packages/react-compass/src/announcement/card/body.tsx, packages/react-compass/src/announcement/card/footer.tsx, packages/react-compass/src/announcement/card/header.tsx, packages/react-compass/src/announcement/card/index.tsx, packages/react-compass/src/appnav/appnav-section.tsx, packages/react-compass/src/appnav/appnav.tsx, packages/react-compass/src/appnav/index.ts, packages/react-compass/src/auto-complete/autoComplete.tsx, packages/react-compass/src/avatar/avatar.tsx, packages/react-compass/src/table/table-cell.tsx, packages/react-compass/src/table/table-checkbox-cell.tsx, packages/react-compass/src/table/table-column-header-filter.tsx, packages/react-compass/src/table/table-column-header.tsx
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> Refactor table

packages/react-compass/src/drawer/drawer.tsx, packages/react-compass/src/drawer/index.ts, packages/react-compass/src/drawer/types.ts
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> fix export error for drawer

packages/react-compass/src/checkbox/checkbox.tsx
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> fix: checkbox unable to change value

apps/docs/data/components/drawer/Drawer.tsx, apps/docs/data/components/drawer/DrawerMode.tsx, apps/docs/data/components/drawer/DrawerPosition.tsx, apps/docs/data/components/drawer/drawer.md, packages/react-compass/src/drawer/constants.ts, packages/react-compass/src/drawer/drawer-default.tsx, packages/react-compass/src/drawer/drawer-footer.tsx, packages/react-compass/src/drawer/drawer-header.tsx, packages/react-compass/src/drawer/drawer-mobile-content.tsx, packages/react-compass/src/drawer/drawer-mobile.tsx, packages/react-compass/src/drawer/drawer.tsx, packages/react-compass/src/drawer/hooks/index.ts, packages/react-compass/src/drawer/hooks/useBackDropStyling.tsx, packages/react-compass/src/drawer/hooks/useScaleEffect.tsx, packages/react-compass/src/drawer/hooks/useSnapPoints.tsx, packages/react-compass/src/drawer/stories/drawer-default.stories.tsx, packages/react-compass/src/drawer/stories/drawer-mobile.stories.tsx, packages/react-compass/src/drawer/styles/drawer-default.module.css, packages/react-compass/src/drawer/styles/drawer-expander.module.css, packages/react-compass/src/drawer/styles/drawer-mobile.module.css, packages/react-compass/src/drawer/styles/drawer-shared.module.css, packages/react-compass/src/drawer/styles/drawer-stories.module.css, packages/react-compass/src/drawer/types.ts, packages/react-compass/src/drawer/utils.ts, packages/react-compass/src/slide-action/slide-action.tsx, packages/react-compass/src/utils/descendant/index.ts, packages/react-compass/src/utils/hooks/useDrag.tsx
**1) Changes**
- Update the documentation page.
- `default` variant: add position `top`.
- `mobile` variant: improve scale effect, and add deceleration drag effect.
- `useDrag`: Switch to Pointer Events, add an option to enable the deceleration effect when exceeding the `limit`.
**2) Impact**
None
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> Drawer Enhancement

packages/react-compass/src/checkbox/checkbox.tsx, packages/react-compass/src/pagination/pagination.hooks.ts
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> fix: checkbox and pagination

apps/docs/data/components/date-picker/MonthPicker.tsx, apps/docs/data/components/date-picker/YearPicker.tsx, apps/docs/data/components/date-picker/date-picker.md, packages/react-compass/src/calendar/calendar-header.tsx, packages/react-compass/src/calendar/calendar-month-grid.tsx, packages/react-compass/src/calendar/calendar-year-grid.tsx, packages/react-compass/src/calendar/calendar.tsx, packages/react-compass/src/calendar/components/date-field.tsx, packages/react-compass/src/calendar/hooks/useMonthYearState.ts, packages/react-compass/src/date-picker/DatePicker.stories.tsx, packages/react-compass/src/date-picker/date-picker.tsx, packages/react-compass/src/date-picker/index.ts
**2) Changes**
**3) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
=> Feature: month & year picker
